import { createServerFn } from "@tanstack/react-start";

export type SupplierEntryKind = "bill" | "payment" | "adjustment";
export type SupplierPayMethod = "cash" | "upi" | "bank_transfer" | "cheque" | "other";
export type SupplierCategory = "stock_gst" | "stock_no_gst" | "expense" | "transport" | "advance" | "drawings" | "other";
export const CATEGORY_LABELS: Record<SupplierCategory, string> = { stock_gst: "Stock purchase (GST bill)", stock_no_gst: "Stock purchase (no GST bill)", expense: "Shop expense", transport: "Transport / freight", advance: "Advance paid", drawings: "Owner withdrawal", other: "Other" };
export const KIND_LABELS: Record<SupplierEntryKind, string> = { bill: "Bill", payment: "Payment", adjustment: "Adjustment" };
export const METHOD_LABELS: Record<SupplierPayMethod, string> = { cash: "Cash", upi: "UPI", bank_transfer: "Bank transfer", cheque: "Cheque", other: "Other" };
export type SupplierSummary = { id: string; name: string; phone: string | null; gstin: string | null; address: string | null; note: string | null; openingBalance: number; paymentTermsDays: number; active: boolean; createdAt: string; totalBilled: number; totalPaid: number; balance: number; lastPaymentOn: string | null; oldestUnsettledDue: string | null };
export type SupplierLedgerItem = { id: string; supplierId: string; supplierName: string; kind: SupplierEntryKind; kindLabel: string; amount: number; category: SupplierCategory; categoryLabel: string; method: SupplierPayMethod | null; methodLabel: string; entryDate: string; dueDate: string | null; billNumber: string | null; reference: string | null; note: string | null; settled: boolean; voidedAt: string | null; voidReason: string | null; recordedBy: string | null; recordedByEmail: string | null; createdAt: string };
export type SupplierLedgerFilters = { from?: string; to?: string; supplierId?: string; kind?: string; category?: string; method?: string; q?: string; showVoided?: boolean; page?: number; pageSize?: number };
export type SupplierLedgerResult = { items: SupplierLedgerItem[]; total: number; totals: { billed: number; paid: number; adjustments: number; net: number } };
export type SupplierLedgerDocument = SupplierLedgerResult & { from: string; to: string };
type Row = Record<string, unknown>;
const text = (value: unknown, max: number) => String(value ?? "").trim().slice(0, max);
const date = (value: unknown) => /^\d{4}-\d{2}-\d{2}$/.test(String(value ?? "")) ? String(value) : null;
const kinds = ["bill", "payment", "adjustment"] as const, categories = ["stock_gst", "stock_no_gst", "expense", "transport", "advance", "drawings", "other"] as const, methods = ["cash", "upi", "bank_transfer", "cheque", "other"] as const;
const allowed = <T extends readonly string[]>(value: unknown, values: T): T[number] | null => values.includes(String(value) as T[number]) ? String(value) as T[number] : null;
const indianToday = () => new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Kolkata", year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date());
async function supplierAdmin() { const { requireStaff, logAudit } = await import("@/lib/staff.server"); const actor = await requireStaff({ capability: "vendor-finance" }); const { supabaseAdmin: sb } = await import("@/integrations/supabase/client.server"); return { sb, actor, logAudit }; }
function listInput(data: { q?: string; page?: number; pageSize?: number } | undefined) { return { q: text(data?.q, 100), page: Math.max(0, Math.floor(Number(data?.page ?? 0))), pageSize: Math.min(100, Math.max(1, Math.floor(Number(data?.pageSize ?? 8)))) }; }
function ledgerInput(data: SupplierLedgerFilters | undefined) { const today = indianToday(); const from = date(data?.from) ?? `${today.slice(0, 8)}01`; const to = date(data?.to) ?? today; const days = Math.round((Date.parse(`${to}T00:00:00Z`) - Date.parse(`${from}T00:00:00Z`)) / 86400000); if (days < 0 || days > 366) throw new Error("The report period must be between 1 and 367 days."); return { from, to, supplierId: text(data?.supplierId, 40) || null, kind: allowed(data?.kind, kinds), category: allowed(data?.category, categories), method: allowed(data?.method, methods), q: text(data?.q, 120), showVoided: Boolean(data?.showVoided), page: Math.max(0, Math.floor(Number(data?.page ?? 0))), pageSize: Math.min(100, Math.max(1, Math.floor(Number(data?.pageSize ?? 8)))) }; }
const mapSupplier = (r: Row): SupplierSummary => ({ id: String(r['id']), name: String(r['name']), phone: r['phone'] ? String(r['phone']) : null, gstin: r['gstin'] ? String(r['gstin']) : null, address: r['address'] ? String(r['address']) : null, note: r['note'] ? String(r['note']) : null, openingBalance: Number(r['opening_balance'] ?? 0), paymentTermsDays: Number(r['payment_terms_days'] ?? 0), active: Boolean(r['active']), createdAt: String(r['created_at']), totalBilled: Number(r['total_billed'] ?? 0), totalPaid: Number(r['total_paid'] ?? 0), balance: Number(r['balance'] ?? 0), lastPaymentOn: r['last_payment_on'] ? String(r['last_payment_on']) : null, oldestUnsettledDue: r['oldest_unsettled_due'] ? String(r['oldest_unsettled_due']) : null });
const mapLedger = (r: Row): SupplierLedgerItem => { const kind = String(r['kind']) as SupplierEntryKind, category = String(r['category']) as SupplierCategory, method = r['method'] ? String(r['method']) as SupplierPayMethod : null; return { id: String(r['id']), supplierId: String(r['supplier_id']), supplierName: String(r['supplier_name']), kind, kindLabel: KIND_LABELS[kind], amount: Number(r['amount']), category, categoryLabel: CATEGORY_LABELS[category], method, methodLabel: method ? METHOD_LABELS[method] : "—", entryDate: String(r['entry_date']), dueDate: r['due_date'] ? String(r['due_date']) : null, billNumber: r['bill_number'] ? String(r['bill_number']) : null, reference: r['reference'] ? String(r['reference']) : null, note: r['note'] ? String(r['note']) : null, settled: Boolean(r['settled']), voidedAt: r['voided_at'] ? String(r['voided_at']) : null, voidReason: r['void_reason'] ? String(r['void_reason']) : null, recordedBy: r['created_by_name'] ? String(r['created_by_name']) : null, recordedByEmail: r['created_by_email'] ? String(r['created_by_email']) : null, createdAt: String(r['created_at']) }; };

export const listSuppliers = createServerFn({ method: "POST" }).inputValidator(listInput).handler(async ({ data }) => { const { sb } = await supplierAdmin(); const { data: rows, error } = await sb.rpc("supplier_summary_page", { p_offset: data.page * data.pageSize, p_limit: data.pageSize, p_query: data.q }); if (error) throw new Error(error.message); const source = (rows ?? []) as Row[]; return { items: source.map(mapSupplier), total: Number(source[0]?.['total_count'] ?? 0) }; });
export const saveSupplier = createServerFn({ method: "POST" }).inputValidator((data: { id?: string; name: string; phone?: string; gstin?: string; address?: string; note?: string; openingBalance?: number; paymentTermsDays?: number; active?: boolean }) => ({ id: text(data?.id, 40), name: text(data?.name, 120), phone: text(data?.phone, 30), gstin: text(data?.gstin, 30).toUpperCase(), address: text(data?.address, 500), note: text(data?.note, 500), openingBalance: Math.round((Number(data?.openingBalance) || 0) * 100) / 100, paymentTermsDays: Math.min(365, Math.max(0, Math.floor(Number(data?.paymentTermsDays) || 0))), active: data?.active !== false })).handler(async ({ data }) => { const { sb, actor, logAudit } = await supplierAdmin(); if (!data.name) return { ok: false as const, error: "Enter the supplier name." }; const patch = { name: data.name, phone: data.phone || null, gstin: data.gstin || null, address: data.address || null, note: data.note || null, opening_balance: data.openingBalance, payment_terms_days: data.paymentTermsDays, active: data.active }; if (data.id) { const { error } = await sb.from("suppliers").update(patch as never).eq("id", data.id); if (error) return { ok: false as const, error: error.message }; await logAudit(sb as never, actor, "supplier.updated", "suppliers", data.id, patch); return { ok: true as const, id: data.id }; } const { data: row, error } = await sb.from("suppliers").insert(patch as never).select("id").single(); if (error || !row) return { ok: false as const, error: error?.message ?? "Could not add supplier." }; await logAudit(sb as never, actor, "supplier.created", "suppliers", row.id, patch); return { ok: true as const, id: String(row.id) }; });
export const recordSupplierEntry = createServerFn({ method: "POST" }).inputValidator((data: { supplierId: string; kind?: string; amount: number; category?: string; method?: string; entryDate?: string; dueDate?: string; billNumber?: string; reference?: string; note?: string }) => ({ supplierId: text(data?.supplierId, 40), kind: allowed(data?.kind, kinds) ?? "payment", amount: Math.round((Number(data?.amount) || 0) * 100) / 100, category: allowed(data?.category, categories) ?? "other", method: allowed(data?.method, methods), entryDate: date(data?.entryDate) ?? indianToday(), dueDate: date(data?.dueDate), billNumber: text(data?.billNumber, 120), reference: text(data?.reference, 160), note: text(data?.note, 500) })).handler(async ({ data }) => { const { sb, actor, logAudit } = await supplierAdmin(); if (!data.supplierId) return { ok: false as const, error: "Choose a supplier." }; if (data.kind !== "adjustment" && data.amount <= 0) return { ok: false as const, error: "Enter an amount greater than zero." }; if (data.kind === "adjustment" && data.amount === 0) return { ok: false as const, error: "Adjustment cannot be zero." }; const { data: id, error } = await sb.rpc("record_supplier_entry", { p_supplier_id: data.supplierId, p_kind: data.kind, p_amount: data.amount, p_category: data.category, p_method: data.method, p_entry_date: data.entryDate, p_due_date: data.dueDate, p_bill_number: data.billNumber, p_reference: data.reference, p_note: data.note, p_actor_id: actor.userId, p_actor_name: actor.name, p_actor_email: actor.email }); if (error) return { ok: false as const, error: error.message }; await logAudit(sb as never, actor, `supplier.entry.${data.kind}`, "supplier_ledger", String(id), data); let warning: string | undefined; if (data.kind === "payment" && data.method === "cash") { const { data: cashRows } = await sb.from("supplier_ledger").select("amount").eq("supplier_id", data.supplierId).eq("kind", "payment").eq("method", "cash").eq("entry_date", data.entryDate).is("voided_at", null); if ((cashRows ?? []).reduce((sum, row) => sum + Number(row.amount), 0) > 10_000) warning = "Cash payments over ₹10,000 to one supplier in a day are disallowed as an expense under section 40A(3)."; } return { ok: true as const, id: String(id), warning }; });
export const voidSupplierEntry = createServerFn({ method: "POST" }).inputValidator((data: { entryId: string; reason: string }) => ({ entryId: text(data?.entryId, 40), reason: text(data?.reason, 300) })).handler(async ({ data }) => { const { sb, actor, logAudit } = await supplierAdmin(); if (data.reason.length < 3) return { ok: false as const, error: "Add a reason for voiding this entry." }; const { data: changed, error } = await sb.rpc("void_supplier_entry", { p_entry_id: data.entryId, p_reason: data.reason, p_actor_id: actor.userId, p_actor_name: actor.name }); if (error) return { ok: false as const, error: error.message }; if (!changed) return { ok: false as const, error: "This entry is already voided." }; await logAudit(sb as never, actor, "supplier.entry.voided", "supplier_ledger", data.entryId, { reason: data.reason }); return { ok: true as const }; });
async function loadLedger(input: ReturnType<typeof ledgerInput>): Promise<SupplierLedgerResult> { const { sb } = await supplierAdmin(); const { data: rows, error } = await sb.rpc("supplier_ledger_page", { p_from: input.from, p_to: input.to, p_supplier: input.supplierId, p_kind: input.kind, p_category: input.category, p_method: input.method, p_query: input.q, p_show_voided: input.showVoided, p_offset: input.page * input.pageSize, p_limit: input.pageSize }); if (error) throw new Error(error.message); const source = (rows ?? []) as Row[]; return { items: source.map(mapLedger), total: Number(source[0]?.['total_count'] ?? 0), totals: { billed: Number(source[0]?.['total_billed'] ?? 0), paid: Number(source[0]?.['total_paid'] ?? 0), adjustments: Number(source[0]?.['total_adjustments'] ?? 0), net: Number(source[0]?.['net_movement'] ?? 0) } }; }
export const supplierLedger = createServerFn({ method: "POST" }).inputValidator(ledgerInput).handler(({ data }) => loadLedger(data));
async function loadAll(input: ReturnType<typeof ledgerInput>) { const first = await loadLedger({ ...input, page: 0, pageSize: 100 }); const items = [...first.items]; for (let page = 1; page * 100 < first.total; page += 1) items.push(...(await loadLedger({ ...input, page, pageSize: 100 })).items); return { ...first, items }; }
const csvCell = (value: unknown) => `"${String(value ?? "").replace(/"/g, '""')}"`;
export const exportSupplierLedgerCsv = createServerFn({ method: "POST" }).inputValidator(ledgerInput).handler(async ({ data }) => { const report = await loadAll(data); const lines: unknown[][] = [["Supplier ledger", `${data.from} to ${data.to}`], ["Total billed", report.totals.billed], ["Total paid", report.totals.paid], ["Adjustments", report.totals.adjustments], ["Net movement", report.totals.net], [], ["Date", "Supplier", "Type", "Category", "Method", "Bill number", "Reference", "Note", "Amount", "Recorded by", "Staff email", "Voided", "Void reason"], ...report.items.map((r) => [r.entryDate, r.supplierName, r.kindLabel, r.categoryLabel, r.methodLabel, r.billNumber, r.reference, r.note, r.amount, r.recordedBy, r.recordedByEmail, r.voidedAt ? "Yes" : "No", r.voidReason])]; return { csv: lines.map((line) => line.map(csvCell).join(",")).join("\r\n"), fileName: `supplier-ledger-${data.from}-to-${data.to}.csv` }; });
export const exportSupplierLedgerPdf = createServerFn({ method: "POST" }).inputValidator(ledgerInput).handler(async ({ data }) => { const report = await loadAll(data); const { createSupplierLedgerPdf } = await import("@/lib/supplier-ledger-report.server"); const payload: SupplierLedgerDocument = { from: data.from, to: data.to, ...report }; const pdf = await createSupplierLedgerPdf(payload); return { base64: Buffer.from(pdf).toString("base64"), fileName: `supplier-ledger-${data.from}-to-${data.to}.pdf` }; });
