import { createFileRoute } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { Download, FileSpreadsheet, Filter, MoreVertical, Plus, ReceiptText, Search, Truck } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import { ListPager, MANAGE_PAGE_SIZE } from "@/components/manage/ListPager";
import { SparkCharge, SparkRing } from "@/components/site/SparkLoaders";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
import { formatINR } from "@/lib/catalog";
import { MANAGE_QUERY_OPTIONS } from "@/lib/manage-query";
import { CATEGORY_LABELS, KIND_LABELS, METHOD_LABELS, exportSupplierLedgerCsv, exportSupplierLedgerPdf, listSuppliers, recordSupplierEntry, saveSupplier, supplierLedger, voidSupplierEntry, type SupplierEntryKind, type SupplierLedgerItem, type SupplierSummary } from "@/lib/suppliers.functions";

export const Route = createFileRoute("/manage/suppliers")({
  head: () => ({ meta: [
    { title: "Suppliers & Purchases — Shaw Traders EV Manager" },
    { name: "description", content: "Auditable supplier bills, purchases, payments and outstanding balances." },
    { name: "robots", content: "noindex" },
    { property: "og:title", content: "Suppliers & Purchases — Shaw Traders EV Manager" },
    { property: "og:description", content: "Supplier purchases and payment ledger for authorized staff." },
    { property: "og:type", content: "website" },
    { name: "twitter:card", content: "summary" },
  ] }), component: SuppliersPage,
});
const today = () => new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Kolkata", year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date());
const month = () => `${today().slice(0, 8)}01`;
const download = (body: BlobPart, fileName: string, mime: string) => { const url = URL.createObjectURL(new Blob([body], { type: mime })); const a = document.createElement("a"); a.href = url; a.download = fileName; a.click(); URL.revokeObjectURL(url); };
function SuppliersPage() {
  const qc = useQueryClient(), getSuppliers = useServerFn(listSuppliers), getLedger = useServerFn(supplierLedger), getCsv = useServerFn(exportSupplierLedgerCsv), getPdf = useServerFn(exportSupplierLedgerPdf);
  const [tab, setTab] = useState("suppliers"), [supplierPage, setSupplierPage] = useState(0), [ledgerPage, setLedgerPage] = useState(0), [q, setQ] = useState("");
  const [from, setFrom] = useState(month()), [to, setTo] = useState(today()), [supplierId, setSupplierId] = useState("all"), [kind, setKind] = useState("all"), [category, setCategory] = useState("all"), [method, setMethod] = useState("all"), [ledgerQ, setLedgerQ] = useState(""), [showVoided, setShowVoided] = useState(false);
  const [supplierSheet, setSupplierSheet] = useState<SupplierSummary | "new" | null>(null), [entrySupplier, setEntrySupplier] = useState<string | null>(null), [entryKind, setEntryKind] = useState<SupplierEntryKind>("payment"), [voidRow, setVoidRow] = useState<SupplierLedgerItem | null>(null), [exporting, setExporting] = useState<string | null>(null);
  const suppliers = useQuery({ queryKey: ["suppliers", q, supplierPage], queryFn: () => getSuppliers({ data: { q, page: supplierPage, pageSize: MANAGE_PAGE_SIZE } }), placeholderData: (old) => old, ...MANAGE_QUERY_OPTIONS });
  const choices = useQuery({ queryKey: ["supplier-choices"], queryFn: () => getSuppliers({ data: { page: 0, pageSize: 100 } }), ...MANAGE_QUERY_OPTIONS });
  const filters = { from, to, supplierId: supplierId === "all" ? undefined : supplierId, kind: kind === "all" ? undefined : kind, category: category === "all" ? undefined : category, method: method === "all" ? undefined : method, q: ledgerQ, showVoided, page: ledgerPage, pageSize: MANAGE_PAGE_SIZE };
  const ledger = useQuery({ queryKey: ["supplier-ledger", filters], queryFn: () => getLedger({ data: filters }), placeholderData: (old) => old, enabled: from <= to, ...MANAGE_QUERY_OPTIONS });
  const refresh = async () => { await Promise.all([qc.invalidateQueries({ queryKey: ["suppliers"] }), qc.invalidateQueries({ queryKey: ["supplier-choices"] }), qc.invalidateQueries({ queryKey: ["supplier-ledger"] })]); };
  async function exportFile(type: "csv" | "pdf") { setExporting(type); try { if (type === "csv") { const r = await getCsv({ data: filters }); download(r.csv, r.fileName, "text/csv;charset=utf-8"); } else { const r = await getPdf({ data: filters }); download(Uint8Array.from(atob(r.base64), c => c.charCodeAt(0)), r.fileName, "application/pdf"); } toast.success(`${type.toUpperCase()} downloaded`); } catch (e) { toast.error(e instanceof Error ? e.message : "Download failed"); } finally { setExporting(null); } }
  return <div className="space-y-6">
    <header className="flex flex-wrap items-start justify-between gap-4 border-b pb-5"><div><div className="flex items-center gap-2"><Truck className="size-6 text-primary"/><h2 className="font-display text-2xl font-bold">Suppliers & Purchases</h2></div><p className="mt-1 text-sm text-muted-foreground">Track supplier bills, payments and balances without mixing customer collections.</p></div><div className="flex gap-2"><Button variant="outline" onClick={() => setSupplierSheet("new")}><Plus className="size-4"/> Supplier</Button><Button onClick={() => { setEntryKind("payment"); setEntrySupplier(choices.data?.items[0]?.id ?? ""); }} disabled={!choices.data?.items.length}><Plus className="size-4"/> Entry</Button></div></header>
    <Tabs value={tab} onValueChange={setTab}><TabsList className="grid h-auto w-full grid-cols-2 sm:w-auto"><TabsTrigger value="suppliers">Suppliers</TabsTrigger><TabsTrigger value="ledger">Payments & bills</TabsTrigger></TabsList>
      <TabsContent value="suppliers" className="space-y-4 pt-3"><div className="relative max-w-md"><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground"/><Input value={q} onChange={e => { setQ(e.target.value); setSupplierPage(0); }} placeholder="Search name, phone or GSTIN" className="pl-9"/></div>{suppliers.isPending || !suppliers.data ? <SparkCharge compact label="Loading suppliers…"/> : suppliers.data.items.length === 0 ? <Empty text="No suppliers found."/> : <><div className="hidden overflow-x-auto rounded-md border md:block"><table className="w-full min-w-[820px] text-sm"><thead className="bg-muted text-left text-xs uppercase text-muted-foreground"><tr><Th>Supplier</Th><Th>Billed</Th><Th>Paid</Th><Th>Outstanding</Th><Th>Last payment</Th><Th><span className="sr-only">Actions</span></Th></tr></thead><tbody>{suppliers.data.items.map(s => <SupplierRow key={s.id} s={s} open={() => setSupplierSheet(s)} record={(k) => { setEntryKind(k); setEntrySupplier(s.id); }} ledger={() => { setSupplierId(s.id); setLedgerPage(0); setTab("ledger"); }}/>)}</tbody></table></div><div className="space-y-3 md:hidden">{suppliers.data.items.map(s => <SupplierCard key={s.id} s={s} open={() => setSupplierSheet(s)} record={(k) => { setEntryKind(k); setEntrySupplier(s.id); }} ledger={() => { setSupplierId(s.id); setLedgerPage(0); setTab("ledger"); }}/>)}</div><ListPager page={supplierPage} total={suppliers.data.total} busy={suppliers.isFetching} onPage={setSupplierPage}/></>}
      </TabsContent>
      <TabsContent value="ledger" className="space-y-5 pt-3"><div className="flex flex-wrap items-end justify-between gap-3"><div className="hidden flex-wrap items-end gap-2 md:flex"><LedgerFilters {...{ from,to,setFrom,setTo,supplierId,setSupplierId,kind,setKind,category,setCategory,method,setMethod,ledgerQ,setLedgerQ,showVoided,setShowVoided,suppliers: choices.data?.items ?? [], resetPage:()=>setLedgerPage(0) }}/></div><MobileFilters content={<LedgerFilters {...{ from,to,setFrom,setTo,supplierId,setSupplierId,kind,setKind,category,setCategory,method,setMethod,ledgerQ,setLedgerQ,showVoided,setShowVoided,suppliers: choices.data?.items ?? [], resetPage:()=>setLedgerPage(0) }}/>}/><div className="flex gap-2"><Button size="sm" variant="outline" disabled={Boolean(exporting)} onClick={() => void exportFile("csv")}>{exporting === "csv" ? <SparkRing/> : <FileSpreadsheet className="size-4"/>} CSV</Button><Button size="sm" disabled={Boolean(exporting)} onClick={() => void exportFile("pdf")}>{exporting === "pdf" ? <SparkRing/> : <Download className="size-4"/>} PDF</Button></div></div>
        {from > to && <p className="text-sm text-destructive">The From date must be before the To date.</p>}{ledger.isPending || !ledger.data ? <SparkCharge compact label="Loading supplier ledger…"/> : <><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Billed" value={formatINR(ledger.data.totals.billed)}/><Metric label="Paid" value={formatINR(ledger.data.totals.paid)}/><Metric label="Adjustments" value={formatINR(ledger.data.totals.adjustments)}/><Metric label="Net movement" value={formatINR(ledger.data.totals.net)}/></div>{ledger.data.items.length === 0 ? <Empty text="No entries match these filters."/> : <><div className="hidden overflow-x-auto rounded-md border md:block"><LedgerTable rows={ledger.data.items} onVoid={setVoidRow}/></div><div className="space-y-3 md:hidden">{ledger.data.items.map(r => <LedgerCard key={r.id} row={r} onVoid={() => setVoidRow(r)}/>)}</div><ListPager page={ledgerPage} total={ledger.data.total} busy={ledger.isFetching} onPage={setLedgerPage}/></>}</>}
      </TabsContent></Tabs>
    <SupplierSheet target={supplierSheet} onClose={() => setSupplierSheet(null)} onSaved={async()=>{setSupplierSheet(null);await refresh();}}/>
    <EntrySheet supplierId={entrySupplier} kind={entryKind} suppliers={choices.data?.items ?? []} onClose={()=>setEntrySupplier(null)} onSaved={async(warning)=>{setEntrySupplier(null);await refresh();toast.success("Entry recorded");if(warning)toast.warning(warning,{duration:8000});}}/>
    <VoidDialog row={voidRow} onClose={()=>setVoidRow(null)} onDone={async()=>{setVoidRow(null);await refresh();}}/>
  </div>;
}
function Actions({ edit, record, ledger }: { edit:()=>void; record:(k:SupplierEntryKind)=>void; ledger:()=>void }) { return <DropdownMenu><DropdownMenuTrigger asChild><Button size="icon" variant="ghost" aria-label="Supplier actions"><MoreVertical className="size-4"/></Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onClick={edit}>Edit supplier</DropdownMenuItem><DropdownMenuItem onClick={()=>record("bill")}>Record bill</DropdownMenuItem><DropdownMenuItem onClick={()=>record("payment")}>Record payment</DropdownMenuItem><DropdownMenuItem onClick={ledger}>View ledger</DropdownMenuItem></DropdownMenuContent></DropdownMenu>; }
function SupplierRow({s,open,record,ledger}:{s:SupplierSummary;open:()=>void;record:(k:SupplierEntryKind)=>void;ledger:()=>void}) { return <tr className="border-t"><Td><strong>{s.name}</strong><span>{s.phone ?? s.gstin ?? "—"}</span></Td><Td>{formatINR(s.totalBilled)}</Td><Td>{formatINR(s.totalPaid)}</Td><Td><strong className={s.balance>0?"text-destructive":""}>{formatINR(s.balance)}</strong></Td><Td>{s.lastPaymentOn ?? "—"}</Td><Td><Actions edit={open} record={record} ledger={ledger}/></Td></tr>; }
function SupplierCard({s,open,record,ledger}:{s:SupplierSummary;open:()=>void;record:(k:SupplierEntryKind)=>void;ledger:()=>void}) { return <article className="rounded-md border p-4"><div className="flex justify-between gap-3"><div><h3 className="font-semibold">{s.name}</h3><p className="text-xs text-muted-foreground">{s.phone ?? s.gstin ?? "No contact details"}</p></div><Actions edit={open} record={record} ledger={ledger}/></div><div className="mt-4 grid grid-cols-3 gap-2 text-xs"><Stat label="Billed" value={formatINR(s.totalBilled)}/><Stat label="Paid" value={formatINR(s.totalPaid)}/><Stat label="Outstanding" value={formatINR(s.balance)}/></div></article>; }
function SupplierSheet({target,onClose,onSaved}:{target:SupplierSummary|"new"|null;onClose:()=>void;onSaved:()=>Promise<void>}) { const fn=useServerFn(saveSupplier); const mutation=useMutation({mutationFn:(data:Parameters<typeof saveSupplier>[0]["data"])=>fn({data}),onSuccess:async r=>{if(!r.ok)return toast.error(r.error);toast.success(target==="new"?"Supplier added":"Supplier updated");await onSaved();}}); const [form,setForm]=useState({name:"",phone:"",gstin:"",address:"",note:"",openingBalance:"0",paymentTermsDays:"0",active:true}); useEffect(()=>{if(target&&target!=="new")setForm({name:target.name,phone:target.phone??"",gstin:target.gstin??"",address:target.address??"",note:target.note??"",openingBalance:String(target.openingBalance),paymentTermsDays:String(target.paymentTermsDays),active:target.active});else if(target==="new")setForm({name:"",phone:"",gstin:"",address:"",note:"",openingBalance:"0",paymentTermsDays:"0",active:true});},[target]); return <Sheet open={Boolean(target)} onOpenChange={o=>!o&&onClose()}><SheetContent className="w-full overflow-y-auto sm:max-w-lg"><SheetHeader><SheetTitle>{target==="new"?"Add supplier":"Edit supplier"}</SheetTitle><SheetDescription>Only the supplier name is required.</SheetDescription></SheetHeader><form className="mt-6 space-y-4" onSubmit={e=>{e.preventDefault();mutation.mutate({id:target!=="new"?target?.id:undefined,name:form.name,phone:form.phone,gstin:form.gstin,address:form.address,note:form.note,openingBalance:Number(form.openingBalance),paymentTermsDays:Number(form.paymentTermsDays),active:form.active});}}><Field label="Name" required value={form.name} onChange={v=>setForm({...form,name:v})}/><div className="grid gap-4 sm:grid-cols-2"><Field label="Phone" value={form.phone} onChange={v=>setForm({...form,phone:v})}/><Field label="GSTIN" value={form.gstin} onChange={v=>setForm({...form,gstin:v})}/></div><Field label="Address" value={form.address} onChange={v=>setForm({...form,address:v})}/><div className="grid gap-4 sm:grid-cols-2"><Field label="Opening balance" type="number" value={form.openingBalance} onChange={v=>setForm({...form,openingBalance:v})}/><Field label="Payment terms (days)" type="number" value={form.paymentTermsDays} onChange={v=>setForm({...form,paymentTermsDays:v})}/></div><div><Label>Note</Label><Textarea value={form.note} onChange={e=>setForm({...form,note:e.target.value})}/></div><Button className="w-full" disabled={mutation.isPending}>{mutation.isPending?<SparkRing/>:null} Save supplier</Button></form></SheetContent></Sheet>; }
function EntrySheet({supplierId,kind,suppliers,onClose,onSaved}:{supplierId:string|null;kind:SupplierEntryKind;suppliers:SupplierSummary[];onClose:()=>void;onSaved:(w?:string)=>Promise<void>}) { const fn=useServerFn(recordSupplierEntry); const mutation=useMutation({mutationFn:(data:Parameters<typeof recordSupplierEntry>[0]["data"])=>fn({data}),onSuccess:async r=>{if(!r.ok)return toast.error(r.error);await onSaved(r.warning);}}); const [form,setForm]=useState({supplierId:"",kind:"payment" as SupplierEntryKind,amount:"",category:"other",method:"cash",entryDate:today(),dueDate:"",billNumber:"",reference:"",note:""}); useEffect(()=>{if(supplierId)setForm({supplierId,kind,amount:"",category:"other",method:"cash",entryDate:today(),dueDate:"",billNumber:"",reference:"",note:""});},[supplierId,kind]); return <Sheet open={Boolean(supplierId)} onOpenChange={o=>!o&&onClose()}><SheetContent className="w-full overflow-y-auto sm:max-w-lg"><SheetHeader><SheetTitle>Record supplier entry</SheetTitle><SheetDescription>Payments need only a supplier and amount.</SheetDescription></SheetHeader><form className="mt-6 space-y-4" onSubmit={e=>{e.preventDefault();mutation.mutate({...form,amount:Number(form.amount),dueDate:form.dueDate||undefined});}}><SelectField label="Supplier" value={form.supplierId} onChange={v=>setForm({...form,supplierId:v})} options={suppliers.map(s=>[s.id,s.name])}/><SelectField label="Type" value={form.kind} onChange={v=>setForm({...form,kind:v as SupplierEntryKind})} options={Object.entries(KIND_LABELS)}/><Field label="Amount" required type="number" value={form.amount} onChange={v=>setForm({...form,amount:v})}/><SelectField label="Category" value={form.category} onChange={v=>setForm({...form,category:v})} options={Object.entries(CATEGORY_LABELS)}/>{form.kind!=="bill"&&<SelectField label="Payment method" value={form.method} onChange={v=>setForm({...form,method:v})} options={Object.entries(METHOD_LABELS)}/>}<div className="grid gap-4 sm:grid-cols-2"><Field label="Entry date" type="date" value={form.entryDate} onChange={v=>setForm({...form,entryDate:v})}/>{form.kind==="bill"&&<Field label="Due date" type="date" value={form.dueDate} onChange={v=>setForm({...form,dueDate:v})}/>}</div><div className="grid gap-4 sm:grid-cols-2"><Field label="Bill number" value={form.billNumber} onChange={v=>setForm({...form,billNumber:v})}/><Field label="Reference" value={form.reference} onChange={v=>setForm({...form,reference:v})}/></div><div><Label>Note</Label><Textarea value={form.note} onChange={e=>setForm({...form,note:e.target.value})}/></div><Button className="w-full" disabled={mutation.isPending}>{mutation.isPending?<SparkRing/>:null} Record entry</Button></form></SheetContent></Sheet>; }
function VoidDialog({row,onClose,onDone}:{row:SupplierLedgerItem|null;onClose:()=>void;onDone:()=>Promise<void>}) { const fn=useServerFn(voidSupplierEntry),[reason,setReason]=useState(""); const mutation=useMutation({mutationFn:()=>fn({data:{entryId:row?.id??"",reason}}),onSuccess:async r=>{if(!r.ok)return toast.error(r.error);toast.success("Entry voided");setReason("");await onDone();}}); return <AlertDialog open={Boolean(row)} onOpenChange={o=>!o&&onClose()}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Void this {row?.kindLabel.toLowerCase()}?</AlertDialogTitle><AlertDialogDescription>The original entry remains in the audit trail and balances will be recalculated.</AlertDialogDescription></AlertDialogHeader><div><Label htmlFor="void-reason">Reason</Label><Textarea id="void-reason" value={reason} onChange={e=>setReason(e.target.value)} placeholder="Why is this entry being voided?"/></div><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction className="bg-destructive text-destructive-foreground hover:bg-destructive/90" disabled={mutation.isPending||reason.trim().length<3} onClick={()=>mutation.mutate()}>Void entry</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>; }
function LedgerFilters(p:{from:string;to:string;setFrom:(v:string)=>void;setTo:(v:string)=>void;supplierId:string;setSupplierId:(v:string)=>void;kind:string;setKind:(v:string)=>void;category:string;setCategory:(v:string)=>void;method:string;setMethod:(v:string)=>void;ledgerQ:string;setLedgerQ:(v:string)=>void;showVoided:boolean;setShowVoided:(v:boolean)=>void;suppliers:SupplierSummary[];resetPage:()=>void}) { const set=(fn:(v:string)=>void)=>(v:string)=>{fn(v);p.resetPage();}; return <><label className="text-xs font-medium text-muted-foreground">From<Input type="date" value={p.from} onChange={e=>set(p.setFrom)(e.target.value)}/></label><label className="text-xs font-medium text-muted-foreground">To<Input type="date" value={p.to} onChange={e=>set(p.setTo)(e.target.value)}/></label><CompactSelect label="Supplier" value={p.supplierId} set={set(p.setSupplierId)} options={[["all","All suppliers"],...p.suppliers.map(s=>[s.id,s.name])]}/><CompactSelect label="Type" value={p.kind} set={set(p.setKind)} options={[["all","All types"],...Object.entries(KIND_LABELS)]}/><CompactSelect label="Category" value={p.category} set={set(p.setCategory)} options={[["all","All categories"],...Object.entries(CATEGORY_LABELS)]}/><CompactSelect label="Method" value={p.method} set={set(p.setMethod)} options={[["all","All methods"],...Object.entries(METHOD_LABELS)]}/><label className="text-xs font-medium text-muted-foreground">Search<Input value={p.ledgerQ} onChange={e=>set(p.setLedgerQ)(e.target.value)} placeholder="Bill, reference, note"/></label><label className="flex items-center gap-2 pb-2 text-sm"><Checkbox checked={p.showVoided} onCheckedChange={v=>{p.setShowVoided(v===true);p.resetPage();}}/>Show voided</label></>; }
function MobileFilters({content}:{content:React.ReactNode}) { const [open,setOpen]=useState(false); return <div className="md:hidden"><Button variant="outline" size="sm" onClick={()=>setOpen(true)}><Filter className="size-4"/> Filters</Button><Sheet open={open} onOpenChange={setOpen}><SheetContent side="bottom" className="max-h-[90vh] overflow-y-auto"><SheetHeader><SheetTitle>Filter payments & bills</SheetTitle><SheetDescription>Filters also apply to CSV and PDF downloads.</SheetDescription></SheetHeader><div className="mt-5 grid gap-4">{content}</div><Button className="mt-5 w-full" onClick={()=>setOpen(false)}>View results</Button></SheetContent></Sheet></div>; }
function LedgerTable({rows,onVoid}:{rows:SupplierLedgerItem[];onVoid:(r:SupplierLedgerItem)=>void}) { return <table className="w-full min-w-[1050px] text-sm"><thead className="bg-muted text-left text-xs uppercase text-muted-foreground"><tr><Th>Date</Th><Th>Supplier</Th><Th>Type</Th><Th>Category</Th><Th>Method</Th><Th>Reference</Th><Th>Recorded by</Th><Th>Amount</Th><Th><span className="sr-only">Actions</span></Th></tr></thead><tbody>{rows.map(r=><tr key={r.id} className={`border-t ${r.voidedAt?"text-muted-foreground line-through":""}`} title={r.voidedAt?r.voidReason??"Voided":undefined}><Td>{r.entryDate}</Td><Td><strong>{r.supplierName}</strong></Td><Td><Badge variant="outline">{r.kindLabel}</Badge>{r.kind==="bill"&&<span>{r.settled?"Settled":"Outstanding"}</span>}</Td><Td>{r.categoryLabel}</Td><Td>{r.methodLabel}</Td><Td>{r.billNumber??r.reference??r.note??"—"}</Td><Td>{r.recordedBy??"—"}<span>{r.recordedByEmail}</span></Td><Td><strong>{formatINR(r.amount)}</strong></Td><Td>{!r.voidedAt&&<Button variant="ghost" size="sm" onClick={()=>onVoid(r)}>Void</Button>}</Td></tr>)}</tbody></table>; }
function LedgerCard({row,onVoid}:{row:SupplierLedgerItem;onVoid:()=>void}) { return <article className={`rounded-md border p-4 ${row.voidedAt?"text-muted-foreground line-through":""}`} title={row.voidReason??undefined}><div className="flex justify-between gap-3"><div><h3 className="font-semibold">{row.supplierName}</h3><p className="text-xs text-muted-foreground">{row.entryDate} · {row.categoryLabel}</p></div><strong>{formatINR(row.amount)}</strong></div><div className="mt-3 flex items-center justify-between"><Badge variant="outline">{row.kindLabel}</Badge>{!row.voidedAt&&<Button size="sm" variant="ghost" onClick={onVoid}>Void</Button>}</div></article>; }
function Field({label,value,onChange,type="text",required=false}:{label:string;value:string;onChange:(v:string)=>void;type?:string;required?:boolean}) { return <label className="grid gap-1.5 text-sm font-medium">{label}<Input type={type} required={required} value={value} onChange={e=>onChange(e.target.value)}/></label>; }
function SelectField({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:Array<[string,string]>}) { return <div className="grid gap-1.5"><Label>{label}</Label><Select value={value} onValueChange={onChange}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{options.map(([v,l])=><SelectItem key={v} value={v}>{l}</SelectItem>)}</SelectContent></Select></div>; }
function CompactSelect({label,value,set,options}:{label:string;value:string;set:(v:string)=>void;options:Array<[string,string]>}) { return <div className="min-w-36"><Label className="text-xs text-muted-foreground">{label}</Label><Select value={value} onValueChange={set}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{options.map(([v,l])=><SelectItem key={v} value={v}>{l}</SelectItem>)}</SelectContent></Select></div>; }
function Metric({label,value}:{label:string;value:string}) { return <div className="border-l-4 border-primary bg-muted/40 p-4"><p className="text-xs font-semibold uppercase text-muted-foreground">{label}</p><p className="mt-1 text-xl font-bold">{value}</p></div>; }
function Stat({label,value}:{label:string;value:string}) { return <div><span className="text-muted-foreground">{label}</span><strong className="mt-1 block">{value}</strong></div>; }
function Empty({text}:{text:string}) { return <div className="border-y border-dashed py-12 text-center text-sm text-muted-foreground"><ReceiptText className="mx-auto mb-2 size-6"/>{text}</div>; }
function Th({children}:{children:React.ReactNode}) { return <th className="px-3 py-2">{children}</th>; }
function Td({children}:{children:React.ReactNode}) { return <td className="px-3 py-2 align-top">{children}</td>; }
