import { useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { listBookingReceipts, recordBookingReceipt, voidBookingReceipt } from "@/lib/vehicles-admin.functions";
import { formatINR } from "@/lib/catalog";
import { roleAtLeast, type StaffRole } from "@/lib/staff-permissions";

export function BookingReceipts({ bookingId, role }: { bookingId: string; role: StaffRole }) {
  const qc = useQueryClient(); const { data, error } = useQuery({ queryKey:["booking-receipts",bookingId], queryFn:() => listBookingReceipts({data:{bookingId}}) });
  const [adding,setAdding] = useState(false); const [voidId,setVoidId] = useState(""); const [reason,setReason] = useState(""); const [msg,setMsg] = useState("");
  const refresh = async () => { await qc.invalidateQueries({queryKey:["booking-receipts",bookingId]}); await qc.invalidateQueries({queryKey:["bookings"]}); };
  return <div className="mt-4 border-t border-border pt-3"><div className="flex flex-wrap items-center justify-between gap-3"><p className="font-semibold">Outstanding {data ? formatINR(data.outstanding) : "…"}</p><Button variant="outline" size="sm" onClick={() => setAdding(!adding)}>Add receipt</Button></div>{error && <p role="alert" className="text-destructive">Could not load receipts.</p>}{data?.receipts.map(r => <div key={r.id} className="flex flex-wrap justify-between gap-2 border-b border-border py-2 text-sm"><div className={r.voided_at ? "text-muted-foreground line-through" : ""}>{formatINR(Number(r.amount))} · {r.payer_type} · {r.method} · {r.received_on}<p className="text-xs text-muted-foreground">{r.reference} · {r.recorded_by_name}{r.note ? ` · ${r.note}` : ""}</p></div>{r.voided_at ? <p className="text-xs text-destructive">Voided: {r.void_reason}</p> : roleAtLeast(role,"manager") && <Button variant="ghost" size="sm" onClick={() => {setVoidId(r.id);setReason("");}}>Void</Button>}</div>)}{voidId && <form className="mt-2 flex gap-2" onSubmit={async e => {e.preventDefault();try {const r=await voidBookingReceipt({data:{receiptId:voidId,reason}});if(!r.ok) setMsg(r.error ?? "Could not void.");else {setVoidId("");await refresh();}}catch(err){setMsg(err instanceof Error ? err.message : "Could not void.");}}}><Input aria-label="Void reason" required minLength={3} value={reason} onChange={e=>setReason(e.target.value)} /><Button variant="destructive">Confirm void</Button><Button type="button" variant="ghost" onClick={()=>setVoidId("")}>Cancel</Button></form>}{adding && <AddBookingReceipt bookingId={bookingId} onDone={async()=>{setAdding(false);await refresh();}} />}{msg && <p role="alert" className="text-destructive">{msg}</p>}</div>;
}
export function AddBookingReceipt({ bookingId,onDone }: { bookingId:string;onDone:()=>void }) {
 const [f,setF]=useState({amount:"",payerType:"customer",method:"cash",reference:"",receivedOn:new Date().toLocaleDateString("en-CA",{timeZone:"Asia/Kolkata"}),note:""}); const [busy,setBusy]=useState(false);const [error,setError]=useState("");
 return <form className="mt-3 grid gap-3 sm:grid-cols-2" onSubmit={async e=>{e.preventDefault();setBusy(true);setError("");try{const r=await recordBookingReceipt({data:{bookingId,...f,amount:Number(f.amount)}});if(!r.ok)setError(r.error ?? "Could not record.");else onDone();}catch(err){setError(err instanceof Error ? err.message : "Could not record.");}finally{setBusy(false);}}}><label className="grid gap-1 text-sm">Amount<Input type="number" min="0.01" step="0.01" required value={f.amount} onChange={e=>setF({...f,amount:e.target.value})}/></label>{([['payerType','Payer',['customer','lender','exchange_setoff']],['method','Method',['cash','upi','bank_transfer','cheque','other']]] as const).map(([key,label,options])=><label className="grid gap-1 text-sm" key={key}>{label}<select className="h-10 rounded-md border border-input bg-background px-3" value={f[key]} onChange={e=>setF({...f,[key]:e.target.value})}>{options.map(o=><option key={o} value={o}>{o.replaceAll('_',' ')}</option>)}</select></label>)}<label className="grid gap-1 text-sm">Received on<Input type="date" required value={f.receivedOn} onChange={e=>setF({...f,receivedOn:e.target.value})}/></label>{(['reference','note'] as const).map(key=><label className="grid gap-1 text-sm capitalize" key={key}>{key}<Input value={f[key]} onChange={e=>setF({...f,[key]:e.target.value})}/></label>)}{error && <p role="alert" className="text-sm text-destructive sm:col-span-2">{error}</p>}<Button disabled={busy}>{busy ? "Recording…" : "Record receipt"}</Button></form>;
}
