/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as BulkRouteImport } from './routes/bulk'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FindPartsRouteImport } from './routes/find-parts'
import { Route as ManageRouteImport } from './routes/manage'
import { Route as ManageLoginRouteImport } from './routes/manage-login'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ReturnsRouteImport } from './routes/returns'
import { Route as ServiceRouteImport } from './routes/service'
import { Route as ShippingRouteImport } from './routes/shipping'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TrackRouteImport } from './routes/track'
import { Route as TradeRouteImport } from './routes/trade'
import { Route as WarrantyRouteImport } from './routes/warranty'
import { Route as BookingTokenRouteImport } from './routes/booking.$token'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as ManageIndexRouteImport } from './routes/manage.index'
import { Route as ManageBookingsRouteImport } from './routes/manage.bookings'
import { Route as ManageCatalogueRouteImport } from './routes/manage.catalogue'
import { Route as ManageCustomersRouteImport } from './routes/manage.customers'
import { Route as ManageDomainRouteImport } from './routes/manage.domain'
import { Route as ManageEnquiriesRouteImport } from './routes/manage.enquiries'
import { Route as ManageHomeRouteImport } from './routes/manage.home'
import { Route as ManageImportRouteImport } from './routes/manage.import'
import { Route as ManageOrdersRouteImport } from './routes/manage.orders'
import { Route as ManageReviewsRouteImport } from './routes/manage.reviews'
import { Route as ManageScootersRouteImport } from './routes/manage.scooters'
import { Route as ManageSettingsRouteImport } from './routes/manage.settings'
import { Route as ManageStaffRouteImport } from './routes/manage.staff'
import { Route as ManageSummaryRouteImport } from './routes/manage.summary'
import { Route as ManageTradeRouteImport } from './routes/manage.trade'
import { Route as OrderIdRouteImport } from './routes/order.$id'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as QuoteTokenRouteImport } from './routes/quote.$token'
import { Route as ScootersIndexRouteImport } from './routes/scooters.index'
import { Route as ScootersSlugRouteImport } from './routes/scooters.$slug'
import { Route as TradePadRouteImport } from './routes/trade.pad'
import { Route as ApiPublicClientErrorRouteImport } from './routes/api/public/client-error'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as ApiPublicRazorpayWebhookRouteImport } from './routes/api/public/razorpay-webhook'
import { Route as ApiPublicCronCartRemindersRouteImport } from './routes/api/public/cron/cart-reminders'
import { Route as ApiPublicCronDailySummaryRouteImport } from './routes/api/public/cron/daily-summary'
import { Route as ApiPublicCronServiceRemindersRouteImport } from './routes/api/public/cron/service-reminders'
import { Route as ApiPublicPhotoSplatRouteImport } from './routes/api/public/photo/$'
import { Route as ApiPublicWhatsappWebhookRouteImport } from './routes/api/public/whatsapp/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const BulkRoute = BulkRouteImport.update({
  id: '/bulk',
  path: '/bulk',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FindPartsRoute = FindPartsRouteImport.update({
  id: '/find-parts',
  path: '/find-parts',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageRoute = ManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageLoginRoute = ManageLoginRouteImport.update({
  id: '/manage-login',
  path: '/manage-login',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRoute = ReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceRoute = ServiceRouteImport.update({
  id: '/service',
  path: '/service',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingRoute = ShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeRoute = TradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => rootRouteImport,
} as any)
const WarrantyRoute = WarrantyRouteImport.update({
  id: '/warranty',
  path: '/warranty',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingTokenRoute = BookingTokenRouteImport.update({
  id: '/booking/$token',
  path: '/booking/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageIndexRoute = ManageIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManageRoute,
} as any)
const ManageBookingsRoute = ManageBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => ManageRoute,
} as any)
const ManageCatalogueRoute = ManageCatalogueRouteImport.update({
  id: '/catalogue',
  path: '/catalogue',
  getParentRoute: () => ManageRoute,
} as any)
const ManageCustomersRoute = ManageCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => ManageRoute,
} as any)
const ManageDomainRoute = ManageDomainRouteImport.update({
  id: '/domain',
  path: '/domain',
  getParentRoute: () => ManageRoute,
} as any)
const ManageEnquiriesRoute = ManageEnquiriesRouteImport.update({
  id: '/enquiries',
  path: '/enquiries',
  getParentRoute: () => ManageRoute,
} as any)
const ManageHomeRoute = ManageHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => ManageRoute,
} as any)
const ManageImportRoute = ManageImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => ManageRoute,
} as any)
const ManageOrdersRoute = ManageOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => ManageRoute,
} as any)
const ManageReviewsRoute = ManageReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => ManageRoute,
} as any)
const ManageScootersRoute = ManageScootersRouteImport.update({
  id: '/scooters',
  path: '/scooters',
  getParentRoute: () => ManageRoute,
} as any)
const ManageSettingsRoute = ManageSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ManageRoute,
} as any)
const ManageStaffRoute = ManageStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => ManageRoute,
} as any)
const ManageSummaryRoute = ManageSummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => ManageRoute,
} as any)
const ManageTradeRoute = ManageTradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => ManageRoute,
} as any)
const OrderIdRoute = OrderIdRouteImport.update({
  id: '/order/$id',
  path: '/order/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteTokenRoute = QuoteTokenRouteImport.update({
  id: '/quote/$token',
  path: '/quote/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ScootersIndexRoute = ScootersIndexRouteImport.update({
  id: '/scooters/',
  path: '/scooters/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScootersSlugRoute = ScootersSlugRouteImport.update({
  id: '/scooters/$slug',
  path: '/scooters/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TradePadRoute = TradePadRouteImport.update({
  id: '/pad',
  path: '/pad',
  getParentRoute: () => TradeRoute,
} as any)
const ApiPublicClientErrorRoute = ApiPublicClientErrorRouteImport.update({
  id: '/api/public/client-error',
  path: '/api/public/client-error',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRazorpayWebhookRoute =
  ApiPublicRazorpayWebhookRouteImport.update({
    id: '/api/public/razorpay-webhook',
    path: '/api/public/razorpay-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronCartRemindersRoute =
  ApiPublicCronCartRemindersRouteImport.update({
    id: '/api/public/cron/cart-reminders',
    path: '/api/public/cron/cart-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronDailySummaryRoute =
  ApiPublicCronDailySummaryRouteImport.update({
    id: '/api/public/cron/daily-summary',
    path: '/api/public/cron/daily-summary',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronServiceRemindersRoute =
  ApiPublicCronServiceRemindersRouteImport.update({
    id: '/api/public/cron/service-reminders',
    path: '/api/public/cron/service-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPhotoSplatRoute = ApiPublicPhotoSplatRouteImport.update({
  id: '/api/public/photo/$',
  path: '/api/public/photo/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWhatsappWebhookRoute =
  ApiPublicWhatsappWebhookRouteImport.update({
    id: '/api/public/whatsapp/webhook',
    path: '/api/public/whatsapp/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/bulk': typeof BulkRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/find-parts': typeof FindPartsRoute
  '/manage': typeof ManageRouteWithChildren
  '/manage-login': typeof ManageLoginRoute
  '/offers': typeof OffersRoute
  '/privacy': typeof PrivacyRoute
  '/returns': typeof ReturnsRoute
  '/service': typeof ServiceRoute
  '/shipping': typeof ShippingRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/track': typeof TrackRoute
  '/trade': typeof TradeRouteWithChildren
  '/warranty': typeof WarrantyRoute
  '/booking/$token': typeof BookingTokenRoute
  '/category/$slug': typeof CategorySlugRoute
  '/manage/bookings': typeof ManageBookingsRoute
  '/manage/catalogue': typeof ManageCatalogueRoute
  '/manage/customers': typeof ManageCustomersRoute
  '/manage/domain': typeof ManageDomainRoute
  '/manage/enquiries': typeof ManageEnquiriesRoute
  '/manage/home': typeof ManageHomeRoute
  '/manage/import': typeof ManageImportRoute
  '/manage/orders': typeof ManageOrdersRoute
  '/manage/reviews': typeof ManageReviewsRoute
  '/manage/scooters': typeof ManageScootersRoute
  '/manage/settings': typeof ManageSettingsRoute
  '/manage/staff': typeof ManageStaffRoute
  '/manage/summary': typeof ManageSummaryRoute
  '/manage/trade': typeof ManageTradeRoute
  '/order/$id': typeof OrderIdRoute
  '/product/$slug': typeof ProductSlugRoute
  '/quote/$token': typeof QuoteTokenRoute
  '/scooters/$slug': typeof ScootersSlugRoute
  '/trade/pad': typeof TradePadRoute
  '/manage/': typeof ManageIndexRoute
  '/scooters/': typeof ScootersIndexRoute
  '/api/public/client-error': typeof ApiPublicClientErrorRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/api/public/cron/cart-reminders': typeof ApiPublicCronCartRemindersRoute
  '/api/public/cron/daily-summary': typeof ApiPublicCronDailySummaryRoute
  '/api/public/cron/service-reminders': typeof ApiPublicCronServiceRemindersRoute
  '/api/public/photo/$': typeof ApiPublicPhotoSplatRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/bulk': typeof BulkRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/find-parts': typeof FindPartsRoute
  '/manage-login': typeof ManageLoginRoute
  '/offers': typeof OffersRoute
  '/privacy': typeof PrivacyRoute
  '/returns': typeof ReturnsRoute
  '/service': typeof ServiceRoute
  '/shipping': typeof ShippingRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/track': typeof TrackRoute
  '/trade': typeof TradeRouteWithChildren
  '/warranty': typeof WarrantyRoute
  '/booking/$token': typeof BookingTokenRoute
  '/category/$slug': typeof CategorySlugRoute
  '/manage/bookings': typeof ManageBookingsRoute
  '/manage/catalogue': typeof ManageCatalogueRoute
  '/manage/customers': typeof ManageCustomersRoute
  '/manage/domain': typeof ManageDomainRoute
  '/manage/enquiries': typeof ManageEnquiriesRoute
  '/manage/home': typeof ManageHomeRoute
  '/manage/import': typeof ManageImportRoute
  '/manage/orders': typeof ManageOrdersRoute
  '/manage/reviews': typeof ManageReviewsRoute
  '/manage/scooters': typeof ManageScootersRoute
  '/manage/settings': typeof ManageSettingsRoute
  '/manage/staff': typeof ManageStaffRoute
  '/manage/summary': typeof ManageSummaryRoute
  '/manage/trade': typeof ManageTradeRoute
  '/order/$id': typeof OrderIdRoute
  '/product/$slug': typeof ProductSlugRoute
  '/quote/$token': typeof QuoteTokenRoute
  '/scooters/$slug': typeof ScootersSlugRoute
  '/trade/pad': typeof TradePadRoute
  '/manage': typeof ManageIndexRoute
  '/scooters': typeof ScootersIndexRoute
  '/api/public/client-error': typeof ApiPublicClientErrorRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/api/public/cron/cart-reminders': typeof ApiPublicCronCartRemindersRoute
  '/api/public/cron/daily-summary': typeof ApiPublicCronDailySummaryRoute
  '/api/public/cron/service-reminders': typeof ApiPublicCronServiceRemindersRoute
  '/api/public/photo/$': typeof ApiPublicPhotoSplatRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/bulk': typeof BulkRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/find-parts': typeof FindPartsRoute
  '/manage': typeof ManageRouteWithChildren
  '/manage-login': typeof ManageLoginRoute
  '/offers': typeof OffersRoute
  '/privacy': typeof PrivacyRoute
  '/returns': typeof ReturnsRoute
  '/service': typeof ServiceRoute
  '/shipping': typeof ShippingRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/track': typeof TrackRoute
  '/trade': typeof TradeRouteWithChildren
  '/warranty': typeof WarrantyRoute
  '/booking/$token': typeof BookingTokenRoute
  '/category/$slug': typeof CategorySlugRoute
  '/manage/bookings': typeof ManageBookingsRoute
  '/manage/catalogue': typeof ManageCatalogueRoute
  '/manage/customers': typeof ManageCustomersRoute
  '/manage/domain': typeof ManageDomainRoute
  '/manage/enquiries': typeof ManageEnquiriesRoute
  '/manage/home': typeof ManageHomeRoute
  '/manage/import': typeof ManageImportRoute
  '/manage/orders': typeof ManageOrdersRoute
  '/manage/reviews': typeof ManageReviewsRoute
  '/manage/scooters': typeof ManageScootersRoute
  '/manage/settings': typeof ManageSettingsRoute
  '/manage/staff': typeof ManageStaffRoute
  '/manage/summary': typeof ManageSummaryRoute
  '/manage/trade': typeof ManageTradeRoute
  '/order/$id': typeof OrderIdRoute
  '/product/$slug': typeof ProductSlugRoute
  '/quote/$token': typeof QuoteTokenRoute
  '/scooters/$slug': typeof ScootersSlugRoute
  '/trade/pad': typeof TradePadRoute
  '/manage/': typeof ManageIndexRoute
  '/scooters/': typeof ScootersIndexRoute
  '/api/public/client-error': typeof ApiPublicClientErrorRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/api/public/cron/cart-reminders': typeof ApiPublicCronCartRemindersRoute
  '/api/public/cron/daily-summary': typeof ApiPublicCronDailySummaryRoute
  '/api/public/cron/service-reminders': typeof ApiPublicCronServiceRemindersRoute
  '/api/public/photo/$': typeof ApiPublicPhotoSplatRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/bulk'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/contact'
    | '/find-parts'
    | '/manage'
    | '/manage-login'
    | '/offers'
    | '/privacy'
    | '/returns'
    | '/service'
    | '/shipping'
    | '/shop'
    | '/sitemap.xml'
    | '/terms'
    | '/track'
    | '/trade'
    | '/warranty'
    | '/booking/$token'
    | '/category/$slug'
    | '/manage/bookings'
    | '/manage/catalogue'
    | '/manage/customers'
    | '/manage/domain'
    | '/manage/enquiries'
    | '/manage/home'
    | '/manage/import'
    | '/manage/orders'
    | '/manage/reviews'
    | '/manage/scooters'
    | '/manage/settings'
    | '/manage/staff'
    | '/manage/summary'
    | '/manage/trade'
    | '/order/$id'
    | '/product/$slug'
    | '/quote/$token'
    | '/scooters/$slug'
    | '/trade/pad'
    | '/manage/'
    | '/scooters/'
    | '/api/public/client-error'
    | '/api/public/health'
    | '/api/public/razorpay-webhook'
    | '/api/public/cron/cart-reminders'
    | '/api/public/cron/daily-summary'
    | '/api/public/cron/service-reminders'
    | '/api/public/photo/$'
    | '/api/public/whatsapp/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/bulk'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/contact'
    | '/find-parts'
    | '/manage-login'
    | '/offers'
    | '/privacy'
    | '/returns'
    | '/service'
    | '/shipping'
    | '/shop'
    | '/sitemap.xml'
    | '/terms'
    | '/track'
    | '/trade'
    | '/warranty'
    | '/booking/$token'
    | '/category/$slug'
    | '/manage/bookings'
    | '/manage/catalogue'
    | '/manage/customers'
    | '/manage/domain'
    | '/manage/enquiries'
    | '/manage/home'
    | '/manage/import'
    | '/manage/orders'
    | '/manage/reviews'
    | '/manage/scooters'
    | '/manage/settings'
    | '/manage/staff'
    | '/manage/summary'
    | '/manage/trade'
    | '/order/$id'
    | '/product/$slug'
    | '/quote/$token'
    | '/scooters/$slug'
    | '/trade/pad'
    | '/manage'
    | '/scooters'
    | '/api/public/client-error'
    | '/api/public/health'
    | '/api/public/razorpay-webhook'
    | '/api/public/cron/cart-reminders'
    | '/api/public/cron/daily-summary'
    | '/api/public/cron/service-reminders'
    | '/api/public/photo/$'
    | '/api/public/whatsapp/webhook'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/bulk'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/contact'
    | '/find-parts'
    | '/manage'
    | '/manage-login'
    | '/offers'
    | '/privacy'
    | '/returns'
    | '/service'
    | '/shipping'
    | '/shop'
    | '/sitemap.xml'
    | '/terms'
    | '/track'
    | '/trade'
    | '/warranty'
    | '/booking/$token'
    | '/category/$slug'
    | '/manage/bookings'
    | '/manage/catalogue'
    | '/manage/customers'
    | '/manage/domain'
    | '/manage/enquiries'
    | '/manage/home'
    | '/manage/import'
    | '/manage/orders'
    | '/manage/reviews'
    | '/manage/scooters'
    | '/manage/settings'
    | '/manage/staff'
    | '/manage/summary'
    | '/manage/trade'
    | '/order/$id'
    | '/product/$slug'
    | '/quote/$token'
    | '/scooters/$slug'
    | '/trade/pad'
    | '/manage/'
    | '/scooters/'
    | '/api/public/client-error'
    | '/api/public/health'
    | '/api/public/razorpay-webhook'
    | '/api/public/cron/cart-reminders'
    | '/api/public/cron/daily-summary'
    | '/api/public/cron/service-reminders'
    | '/api/public/photo/$'
    | '/api/public/whatsapp/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  BulkRoute: typeof BulkRoute
  CartRoute: typeof CartRoute
  CategoriesRoute: typeof CategoriesRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  FindPartsRoute: typeof FindPartsRoute
  ManageRoute: typeof ManageRouteWithChildren
  ManageLoginRoute: typeof ManageLoginRoute
  OffersRoute: typeof OffersRoute
  PrivacyRoute: typeof PrivacyRoute
  ReturnsRoute: typeof ReturnsRoute
  ServiceRoute: typeof ServiceRoute
  ShippingRoute: typeof ShippingRoute
  ShopRoute: typeof ShopRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  TrackRoute: typeof TrackRoute
  TradeRoute: typeof TradeRouteWithChildren
  WarrantyRoute: typeof WarrantyRoute
  BookingTokenRoute: typeof BookingTokenRoute
  CategorySlugRoute: typeof CategorySlugRoute
  OrderIdRoute: typeof OrderIdRoute
  ProductSlugRoute: typeof ProductSlugRoute
  QuoteTokenRoute: typeof QuoteTokenRoute
  ScootersSlugRoute: typeof ScootersSlugRoute
  ScootersIndexRoute: typeof ScootersIndexRoute
  ApiPublicClientErrorRoute: typeof ApiPublicClientErrorRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicRazorpayWebhookRoute: typeof ApiPublicRazorpayWebhookRoute
  ApiPublicCronCartRemindersRoute: typeof ApiPublicCronCartRemindersRoute
  ApiPublicCronDailySummaryRoute: typeof ApiPublicCronDailySummaryRoute
  ApiPublicCronServiceRemindersRoute: typeof ApiPublicCronServiceRemindersRoute
  ApiPublicPhotoSplatRoute: typeof ApiPublicPhotoSplatRoute
  ApiPublicWhatsappWebhookRoute: typeof ApiPublicWhatsappWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulk': {
      id: '/bulk'
      path: '/bulk'
      fullPath: '/bulk'
      preLoaderRoute: typeof BulkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-parts': {
      id: '/find-parts'
      path: '/find-parts'
      fullPath: '/find-parts'
      preLoaderRoute: typeof FindPartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage': {
      id: '/manage'
      path: '/manage'
      fullPath: '/manage'
      preLoaderRoute: typeof ManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage-login': {
      id: '/manage-login'
      path: '/manage-login'
      fullPath: '/manage-login'
      preLoaderRoute: typeof ManageLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns': {
      id: '/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service': {
      id: '/service'
      path: '/service'
      fullPath: '/service'
      preLoaderRoute: typeof ServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping': {
      id: '/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof ShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade': {
      id: '/trade'
      path: '/trade'
      fullPath: '/trade'
      preLoaderRoute: typeof TradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warranty': {
      id: '/warranty'
      path: '/warranty'
      fullPath: '/warranty'
      preLoaderRoute: typeof WarrantyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/$token': {
      id: '/booking/$token'
      path: '/booking/$token'
      fullPath: '/booking/$token'
      preLoaderRoute: typeof BookingTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/': {
      id: '/manage/'
      path: '/'
      fullPath: '/manage/'
      preLoaderRoute: typeof ManageIndexRouteImport
      parentRoute: typeof ManageRoute
    }
    '/manage/bookings': {
      id: '/manage/bookings'
      path: '/bookings'
      fullPath: '/manage/bookings'
      preLoaderRoute: typeof ManageBookingsRouteImport
      parentRoute: typeof ManageRoute
    }
    '/manage/catalogue': {
      id: '/manage/catalogue'
      path: '/catalogue'
      fullPath: '/manage/catalogue'
      preLoaderRoute: typeof ManageCatalogueRouteImport
      parentRoute: typeof ManageRoute
    }
    '/manage/customers': {
      id: '/manage/customers'
      path: '/customers'
      fullPath: '/manage/customers'
      preLoaderRoute: typeof ManageCustomersRouteImport
      parentRoute: typeof ManageRoute
    }
    '/manage/domain': {
      id: '/manage/domain'
      path: '/domain'
      fullPath: '/manage/domain'
      preLoaderRoute: typeof ManageDomainRouteImport
      parentRoute: typeof ManageRoute
    }
    '/manage/enquiries': {
      id: '/manage/enquiries'
      path: '/enquiries'
      fullPath: '/manage/enquiries'
      preLoaderRoute: typeof ManageEnquiriesRouteImport
      parentRoute: typeof ManageRoute
    }
    '/manage/home': {
      id: '/manage/home'
      path: '/home'
      fullPath: '/manage/home'
      preLoaderRoute: typeof ManageHomeRouteImport
      parentRoute: typeof ManageRoute
    }
    '/manage/import': {
      id: '/manage/import'
      path: '/import'
      fullPath: '/manage/import'
      preLoaderRoute: typeof ManageImportRouteImport
      parentRoute: typeof ManageRoute
    }
    '/manage/orders': {
      id: '/manage/orders'
      path: '/orders'
      fullPath: '/manage/orders'
      preLoaderRoute: typeof ManageOrdersRouteImport
      parentRoute: typeof ManageRoute
    }
    '/manage/reviews': {
      id: '/manage/reviews'
      path: '/reviews'
      fullPath: '/manage/reviews'
      preLoaderRoute: typeof ManageReviewsRouteImport
      parentRoute: typeof ManageRoute
    }
    '/manage/scooters': {
      id: '/manage/scooters'
      path: '/scooters'
      fullPath: '/manage/scooters'
      preLoaderRoute: typeof ManageScootersRouteImport
      parentRoute: typeof ManageRoute
    }
    '/manage/settings': {
      id: '/manage/settings'
      path: '/settings'
      fullPath: '/manage/settings'
      preLoaderRoute: typeof ManageSettingsRouteImport
      parentRoute: typeof ManageRoute
    }
    '/manage/staff': {
      id: '/manage/staff'
      path: '/staff'
      fullPath: '/manage/staff'
      preLoaderRoute: typeof ManageStaffRouteImport
      parentRoute: typeof ManageRoute
    }
    '/manage/summary': {
      id: '/manage/summary'
      path: '/summary'
      fullPath: '/manage/summary'
      preLoaderRoute: typeof ManageSummaryRouteImport
      parentRoute: typeof ManageRoute
    }
    '/manage/trade': {
      id: '/manage/trade'
      path: '/trade'
      fullPath: '/manage/trade'
      preLoaderRoute: typeof ManageTradeRouteImport
      parentRoute: typeof ManageRoute
    }
    '/order/$id': {
      id: '/order/$id'
      path: '/order/$id'
      fullPath: '/order/$id'
      preLoaderRoute: typeof OrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote/$token': {
      id: '/quote/$token'
      path: '/quote/$token'
      fullPath: '/quote/$token'
      preLoaderRoute: typeof QuoteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scooters/': {
      id: '/scooters/'
      path: '/scooters'
      fullPath: '/scooters/'
      preLoaderRoute: typeof ScootersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scooters/$slug': {
      id: '/scooters/$slug'
      path: '/scooters/$slug'
      fullPath: '/scooters/$slug'
      preLoaderRoute: typeof ScootersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade/pad': {
      id: '/trade/pad'
      path: '/pad'
      fullPath: '/trade/pad'
      preLoaderRoute: typeof TradePadRouteImport
      parentRoute: typeof TradeRoute
    }
    '/api/public/client-error': {
      id: '/api/public/client-error'
      path: '/api/public/client-error'
      fullPath: '/api/public/client-error'
      preLoaderRoute: typeof ApiPublicClientErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/razorpay-webhook': {
      id: '/api/public/razorpay-webhook'
      path: '/api/public/razorpay-webhook'
      fullPath: '/api/public/razorpay-webhook'
      preLoaderRoute: typeof ApiPublicRazorpayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/cart-reminders': {
      id: '/api/public/cron/cart-reminders'
      path: '/api/public/cron/cart-reminders'
      fullPath: '/api/public/cron/cart-reminders'
      preLoaderRoute: typeof ApiPublicCronCartRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/daily-summary': {
      id: '/api/public/cron/daily-summary'
      path: '/api/public/cron/daily-summary'
      fullPath: '/api/public/cron/daily-summary'
      preLoaderRoute: typeof ApiPublicCronDailySummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/service-reminders': {
      id: '/api/public/cron/service-reminders'
      path: '/api/public/cron/service-reminders'
      fullPath: '/api/public/cron/service-reminders'
      preLoaderRoute: typeof ApiPublicCronServiceRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/photo/$': {
      id: '/api/public/photo/$'
      path: '/api/public/photo/$'
      fullPath: '/api/public/photo/$'
      preLoaderRoute: typeof ApiPublicPhotoSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whatsapp/webhook': {
      id: '/api/public/whatsapp/webhook'
      path: '/api/public/whatsapp/webhook'
      fullPath: '/api/public/whatsapp/webhook'
      preLoaderRoute: typeof ApiPublicWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ManageRouteChildren {
  ManageBookingsRoute: typeof ManageBookingsRoute
  ManageCatalogueRoute: typeof ManageCatalogueRoute
  ManageCustomersRoute: typeof ManageCustomersRoute
  ManageDomainRoute: typeof ManageDomainRoute
  ManageEnquiriesRoute: typeof ManageEnquiriesRoute
  ManageHomeRoute: typeof ManageHomeRoute
  ManageImportRoute: typeof ManageImportRoute
  ManageOrdersRoute: typeof ManageOrdersRoute
  ManageReviewsRoute: typeof ManageReviewsRoute
  ManageScootersRoute: typeof ManageScootersRoute
  ManageSettingsRoute: typeof ManageSettingsRoute
  ManageStaffRoute: typeof ManageStaffRoute
  ManageSummaryRoute: typeof ManageSummaryRoute
  ManageTradeRoute: typeof ManageTradeRoute
  ManageIndexRoute: typeof ManageIndexRoute
}

const ManageRouteChildren: ManageRouteChildren = {
  ManageBookingsRoute: ManageBookingsRoute,
  ManageCatalogueRoute: ManageCatalogueRoute,
  ManageCustomersRoute: ManageCustomersRoute,
  ManageDomainRoute: ManageDomainRoute,
  ManageEnquiriesRoute: ManageEnquiriesRoute,
  ManageHomeRoute: ManageHomeRoute,
  ManageImportRoute: ManageImportRoute,
  ManageOrdersRoute: ManageOrdersRoute,
  ManageReviewsRoute: ManageReviewsRoute,
  ManageScootersRoute: ManageScootersRoute,
  ManageSettingsRoute: ManageSettingsRoute,
  ManageStaffRoute: ManageStaffRoute,
  ManageSummaryRoute: ManageSummaryRoute,
  ManageTradeRoute: ManageTradeRoute,
  ManageIndexRoute: ManageIndexRoute,
}

const ManageRouteWithChildren =
  ManageRoute._addFileChildren(ManageRouteChildren)

interface TradeRouteChildren {
  TradePadRoute: typeof TradePadRoute
}

const TradeRouteChildren: TradeRouteChildren = {
  TradePadRoute: TradePadRoute,
}

const TradeRouteWithChildren = TradeRoute._addFileChildren(TradeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  BulkRoute: BulkRoute,
  CartRoute: CartRoute,
  CategoriesRoute: CategoriesRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  FindPartsRoute: FindPartsRoute,
  ManageRoute: ManageRouteWithChildren,
  ManageLoginRoute: ManageLoginRoute,
  OffersRoute: OffersRoute,
  PrivacyRoute: PrivacyRoute,
  ReturnsRoute: ReturnsRoute,
  ServiceRoute: ServiceRoute,
  ShippingRoute: ShippingRoute,
  ShopRoute: ShopRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  TrackRoute: TrackRoute,
  TradeRoute: TradeRouteWithChildren,
  WarrantyRoute: WarrantyRoute,
  BookingTokenRoute: BookingTokenRoute,
  CategorySlugRoute: CategorySlugRoute,
  OrderIdRoute: OrderIdRoute,
  ProductSlugRoute: ProductSlugRoute,
  QuoteTokenRoute: QuoteTokenRoute,
  ScootersSlugRoute: ScootersSlugRoute,
  ScootersIndexRoute: ScootersIndexRoute,
  ApiPublicClientErrorRoute: ApiPublicClientErrorRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicRazorpayWebhookRoute: ApiPublicRazorpayWebhookRoute,
  ApiPublicCronCartRemindersRoute: ApiPublicCronCartRemindersRoute,
  ApiPublicCronDailySummaryRoute: ApiPublicCronDailySummaryRoute,
  ApiPublicCronServiceRemindersRoute: ApiPublicCronServiceRemindersRoute,
  ApiPublicPhotoSplatRoute: ApiPublicPhotoSplatRoute,
  ApiPublicWhatsappWebhookRoute: ApiPublicWhatsappWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
