/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as BulkRouteImport } from './routes/bulk'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FindPartsRouteImport } from './routes/find-parts'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ManageRouteImport } from './routes/manage'
import { Route as ManageLoginRouteImport } from './routes/manage-login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReturnsRouteImport } from './routes/returns'
import { Route as ServiceRouteImport } from './routes/service'
import { Route as ShippingRouteImport } from './routes/shipping'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TrackRouteImport } from './routes/track'
import { Route as TradeRouteImport } from './routes/trade'
import { Route as WarrantyRouteImport } from './routes/warranty'
import { Route as BookingTokenRouteImport } from './routes/booking.$token'
import { Route as ManageIndexRouteImport } from './routes/manage.index'
import { Route as ManageAboutRouteImport } from './routes/manage.about'
import { Route as ManageAllProductsRouteImport } from './routes/manage.all-products'
import { Route as ManageBookingsRouteImport } from './routes/manage.bookings'
import { Route as ManageBrandCatalogueRouteImport } from './routes/manage.brand-catalogue'
import { Route as ManageCatalogueRouteImport } from './routes/manage.catalogue'
import { Route as ManageCounterSalesRouteImport } from './routes/manage.counter-sales'
import { Route as ManageCustomersRouteImport } from './routes/manage.customers'
import { Route as ManageDomainRouteImport } from './routes/manage.domain'
import { Route as ManageEnquiriesRouteImport } from './routes/manage.enquiries'
import { Route as ManageHomeRouteImport } from './routes/manage.home'
import { Route as ManageImportRouteImport } from './routes/manage.import'
import { Route as ManageOrdersRouteImport } from './routes/manage.orders'
import { Route as ManagePaymentReportsRouteImport } from './routes/manage.payment-reports'
import { Route as ManageRazorpayReviewRouteImport } from './routes/manage.razorpay-review'
import { Route as ManageReviewsRouteImport } from './routes/manage.reviews'
import { Route as ManageScootersRouteImport } from './routes/manage.scooters'
import { Route as ManageSettingsRouteImport } from './routes/manage.settings'
import { Route as ManageStaffRouteImport } from './routes/manage.staff'
import { Route as ManageSummaryRouteImport } from './routes/manage.summary'
import { Route as ManageSuppliersRouteImport } from './routes/manage.suppliers'
import { Route as ManageTradeRouteImport } from './routes/manage.trade'
import { Route as ManageVendorsRouteImport } from './routes/manage.vendors'
import { Route as OrderIdRouteImport } from './routes/order.$id'
import { Route as QuoteTokenRouteImport } from './routes/quote.$token'
import { Route as TradePadRouteImport } from './routes/trade.pad'
import { Route as AuthenticatedCustomerBrandRouteImport } from './routes/_authenticated/_customer/brand'
import { Route as AuthenticatedCustomerCartRouteImport } from './routes/_authenticated/_customer/cart'
import { Route as AuthenticatedCustomerCategoriesRouteImport } from './routes/_authenticated/_customer/categories'
import { Route as AuthenticatedCustomerCheckoutRouteImport } from './routes/_authenticated/_customer/checkout'
import { Route as AuthenticatedCustomerOffersRouteImport } from './routes/_authenticated/_customer/offers'
import { Route as AuthenticatedCustomerShopRouteImport } from './routes/_authenticated/_customer/shop'
import { Route as ApiPublicCatalogueRouteImport } from './routes/api/public/catalogue'
import { Route as ApiPublicClientErrorRouteImport } from './routes/api/public/client-error'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as ApiPublicRazorpayWebhookRouteImport } from './routes/api/public/razorpay-webhook'
import { Route as ManageCustomersIndexRouteImport } from './routes/manage.customers.index'
import { Route as ManageCustomersCustomerIdRouteImport } from './routes/manage.customers.$customerId'
import { Route as ManageOrdersIndexRouteImport } from './routes/manage.orders.index'
import { Route as ManageOrdersOrderIdRouteImport } from './routes/manage.orders.$orderId'
import { Route as ManageProductsProductIdRouteImport } from './routes/manage.products.$productId'
import { Route as AuthenticatedCustomerCategorySlugRouteImport } from './routes/_authenticated/_customer/category.$slug'
import { Route as AuthenticatedCustomerProductSlugRouteImport } from './routes/_authenticated/_customer/product.$slug'
import { Route as AuthenticatedCustomerScootersIndexRouteImport } from './routes/_authenticated/_customer/scooters.index'
import { Route as AuthenticatedCustomerScootersSlugRouteImport } from './routes/_authenticated/_customer/scooters.$slug'
import { Route as ApiPublicCronCartRemindersRouteImport } from './routes/api/public/cron/cart-reminders'
import { Route as ApiPublicCronDailySummaryRouteImport } from './routes/api/public/cron/daily-summary'
import { Route as ApiPublicCronReleaseStaleOrdersRouteImport } from './routes/api/public/cron/release-stale-orders'
import { Route as ApiPublicCronServiceRemindersRouteImport } from './routes/api/public/cron/service-reminders'
import { Route as ApiPublicPhotoSplatRouteImport } from './routes/api/public/photo/$'
import { Route as ApiPublicWhatsappWebhookRouteImport } from './routes/api/public/whatsapp/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const BulkRoute = BulkRouteImport.update({
  id: '/bulk',
  path: '/bulk',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FindPartsRoute = FindPartsRouteImport.update({
  id: '/find-parts',
  path: '/find-parts',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageRoute = ManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageLoginRoute = ManageLoginRouteImport.update({
  id: '/manage-login',
  path: '/manage-login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRoute = ReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceRoute = ServiceRouteImport.update({
  id: '/service',
  path: '/service',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingRoute = ShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeRoute = TradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => rootRouteImport,
} as any)
const WarrantyRoute = WarrantyRouteImport.update({
  id: '/warranty',
  path: '/warranty',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingTokenRoute = BookingTokenRouteImport.update({
  id: '/booking/$token',
  path: '/booking/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageIndexRoute = ManageIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManageRoute,
} as any)
const ManageAboutRoute = ManageAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => ManageRoute,
} as any)
const ManageAllProductsRoute = ManageAllProductsRouteImport.update({
  id: '/all-products',
  path: '/all-products',
  getParentRoute: () => ManageRoute,
} as any)
const ManageBookingsRoute = ManageBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => ManageRoute,
} as any)
const ManageBrandCatalogueRoute = ManageBrandCatalogueRouteImport.update({
  id: '/brand-catalogue',
  path: '/brand-catalogue',
  getParentRoute: () => ManageRoute,
} as any)
const ManageCatalogueRoute = ManageCatalogueRouteImport.update({
  id: '/catalogue',
  path: '/catalogue',
  getParentRoute: () => ManageRoute,
} as any)
const ManageCounterSalesRoute = ManageCounterSalesRouteImport.update({
  id: '/counter-sales',
  path: '/counter-sales',
  getParentRoute: () => ManageRoute,
} as any)
const ManageCustomersRoute = ManageCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => ManageRoute,
} as any)
const ManageDomainRoute = ManageDomainRouteImport.update({
  id: '/domain',
  path: '/domain',
  getParentRoute: () => ManageRoute,
} as any)
const ManageEnquiriesRoute = ManageEnquiriesRouteImport.update({
  id: '/enquiries',
  path: '/enquiries',
  getParentRoute: () => ManageRoute,
} as any)
const ManageHomeRoute = ManageHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => ManageRoute,
} as any)
const ManageImportRoute = ManageImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => ManageRoute,
} as any)
const ManageOrdersRoute = ManageOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => ManageRoute,
} as any)
const ManagePaymentReportsRoute = ManagePaymentReportsRouteImport.update({
  id: '/payment-reports',
  path: '/payment-reports',
  getParentRoute: () => ManageRoute,
} as any)
const ManageRazorpayReviewRoute = ManageRazorpayReviewRouteImport.update({
  id: '/razorpay-review',
  path: '/razorpay-review',
  getParentRoute: () => ManageRoute,
} as any)
const ManageReviewsRoute = ManageReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => ManageRoute,
} as any)
const ManageScootersRoute = ManageScootersRouteImport.update({
  id: '/scooters',
  path: '/scooters',
  getParentRoute: () => ManageRoute,
} as any)
const ManageSettingsRoute = ManageSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ManageRoute,
} as any)
const ManageStaffRoute = ManageStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => ManageRoute,
} as any)
const ManageSummaryRoute = ManageSummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => ManageRoute,
} as any)
const ManageSuppliersRoute = ManageSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => ManageRoute,
} as any)
const ManageTradeRoute = ManageTradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => ManageRoute,
} as any)
const ManageVendorsRoute = ManageVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => ManageRoute,
} as any)
const OrderIdRoute = OrderIdRouteImport.update({
  id: '/order/$id',
  path: '/order/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteTokenRoute = QuoteTokenRouteImport.update({
  id: '/quote/$token',
  path: '/quote/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const TradePadRoute = TradePadRouteImport.update({
  id: '/pad',
  path: '/pad',
  getParentRoute: () => TradeRoute,
} as any)
const AuthenticatedCustomerBrandRoute =
  AuthenticatedCustomerBrandRouteImport.update({
    id: '/_authenticated/_customer/brand',
    path: '/brand',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedCustomerCartRoute =
  AuthenticatedCustomerCartRouteImport.update({
    id: '/_authenticated/_customer/cart',
    path: '/cart',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedCustomerCategoriesRoute =
  AuthenticatedCustomerCategoriesRouteImport.update({
    id: '/_authenticated/_customer/categories',
    path: '/categories',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedCustomerCheckoutRoute =
  AuthenticatedCustomerCheckoutRouteImport.update({
    id: '/_authenticated/_customer/checkout',
    path: '/checkout',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedCustomerOffersRoute =
  AuthenticatedCustomerOffersRouteImport.update({
    id: '/_authenticated/_customer/offers',
    path: '/offers',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedCustomerShopRoute =
  AuthenticatedCustomerShopRouteImport.update({
    id: '/_authenticated/_customer/shop',
    path: '/shop',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCatalogueRoute = ApiPublicCatalogueRouteImport.update({
  id: '/api/public/catalogue',
  path: '/api/public/catalogue',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicClientErrorRoute = ApiPublicClientErrorRouteImport.update({
  id: '/api/public/client-error',
  path: '/api/public/client-error',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRazorpayWebhookRoute =
  ApiPublicRazorpayWebhookRouteImport.update({
    id: '/api/public/razorpay-webhook',
    path: '/api/public/razorpay-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ManageCustomersIndexRoute = ManageCustomersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManageCustomersRoute,
} as any)
const ManageCustomersCustomerIdRoute =
  ManageCustomersCustomerIdRouteImport.update({
    id: '/$customerId',
    path: '/$customerId',
    getParentRoute: () => ManageCustomersRoute,
  } as any)
const ManageOrdersIndexRoute = ManageOrdersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManageOrdersRoute,
} as any)
const ManageOrdersOrderIdRoute = ManageOrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => ManageOrdersRoute,
} as any)
const ManageProductsProductIdRoute = ManageProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => ManageRoute,
} as any)
const AuthenticatedCustomerCategorySlugRoute =
  AuthenticatedCustomerCategorySlugRouteImport.update({
    id: '/_authenticated/_customer/category/$slug',
    path: '/category/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedCustomerProductSlugRoute =
  AuthenticatedCustomerProductSlugRouteImport.update({
    id: '/_authenticated/_customer/product/$slug',
    path: '/product/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedCustomerScootersIndexRoute =
  AuthenticatedCustomerScootersIndexRouteImport.update({
    id: '/_authenticated/_customer/scooters/',
    path: '/scooters/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedCustomerScootersSlugRoute =
  AuthenticatedCustomerScootersSlugRouteImport.update({
    id: '/_authenticated/_customer/scooters/$slug',
    path: '/scooters/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronCartRemindersRoute =
  ApiPublicCronCartRemindersRouteImport.update({
    id: '/api/public/cron/cart-reminders',
    path: '/api/public/cron/cart-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronDailySummaryRoute =
  ApiPublicCronDailySummaryRouteImport.update({
    id: '/api/public/cron/daily-summary',
    path: '/api/public/cron/daily-summary',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronReleaseStaleOrdersRoute =
  ApiPublicCronReleaseStaleOrdersRouteImport.update({
    id: '/api/public/cron/release-stale-orders',
    path: '/api/public/cron/release-stale-orders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronServiceRemindersRoute =
  ApiPublicCronServiceRemindersRouteImport.update({
    id: '/api/public/cron/service-reminders',
    path: '/api/public/cron/service-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPhotoSplatRoute = ApiPublicPhotoSplatRouteImport.update({
  id: '/api/public/photo/$',
  path: '/api/public/photo/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWhatsappWebhookRoute =
  ApiPublicWhatsappWebhookRouteImport.update({
    id: '/api/public/whatsapp/webhook',
    path: '/api/public/whatsapp/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/bulk': typeof BulkRoute
  '/contact': typeof ContactRoute
  '/find-parts': typeof FindPartsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/manage': typeof ManageRouteWithChildren
  '/manage-login': typeof ManageLoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/returns': typeof ReturnsRoute
  '/service': typeof ServiceRoute
  '/shipping': typeof ShippingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/track': typeof TrackRoute
  '/trade': typeof TradeRouteWithChildren
  '/warranty': typeof WarrantyRoute
  '/booking/$token': typeof BookingTokenRoute
  '/manage/about': typeof ManageAboutRoute
  '/manage/all-products': typeof ManageAllProductsRoute
  '/manage/bookings': typeof ManageBookingsRoute
  '/manage/brand-catalogue': typeof ManageBrandCatalogueRoute
  '/manage/catalogue': typeof ManageCatalogueRoute
  '/manage/counter-sales': typeof ManageCounterSalesRoute
  '/manage/customers': typeof ManageCustomersRouteWithChildren
  '/manage/domain': typeof ManageDomainRoute
  '/manage/enquiries': typeof ManageEnquiriesRoute
  '/manage/home': typeof ManageHomeRoute
  '/manage/import': typeof ManageImportRoute
  '/manage/orders': typeof ManageOrdersRouteWithChildren
  '/manage/payment-reports': typeof ManagePaymentReportsRoute
  '/manage/razorpay-review': typeof ManageRazorpayReviewRoute
  '/manage/reviews': typeof ManageReviewsRoute
  '/manage/scooters': typeof ManageScootersRoute
  '/manage/settings': typeof ManageSettingsRoute
  '/manage/staff': typeof ManageStaffRoute
  '/manage/summary': typeof ManageSummaryRoute
  '/manage/suppliers': typeof ManageSuppliersRoute
  '/manage/trade': typeof ManageTradeRoute
  '/manage/vendors': typeof ManageVendorsRoute
  '/order/$id': typeof OrderIdRoute
  '/quote/$token': typeof QuoteTokenRoute
  '/trade/pad': typeof TradePadRoute
  '/manage/': typeof ManageIndexRoute
  '/brand': typeof AuthenticatedCustomerBrandRoute
  '/cart': typeof AuthenticatedCustomerCartRoute
  '/categories': typeof AuthenticatedCustomerCategoriesRoute
  '/checkout': typeof AuthenticatedCustomerCheckoutRoute
  '/offers': typeof AuthenticatedCustomerOffersRoute
  '/shop': typeof AuthenticatedCustomerShopRoute
  '/api/public/catalogue': typeof ApiPublicCatalogueRoute
  '/api/public/client-error': typeof ApiPublicClientErrorRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/manage/customers/$customerId': typeof ManageCustomersCustomerIdRoute
  '/manage/orders/$orderId': typeof ManageOrdersOrderIdRoute
  '/manage/products/$productId': typeof ManageProductsProductIdRoute
  '/manage/customers/': typeof ManageCustomersIndexRoute
  '/manage/orders/': typeof ManageOrdersIndexRoute
  '/category/$slug': typeof AuthenticatedCustomerCategorySlugRoute
  '/product/$slug': typeof AuthenticatedCustomerProductSlugRoute
  '/scooters/$slug': typeof AuthenticatedCustomerScootersSlugRoute
  '/api/public/cron/cart-reminders': typeof ApiPublicCronCartRemindersRoute
  '/api/public/cron/daily-summary': typeof ApiPublicCronDailySummaryRoute
  '/api/public/cron/release-stale-orders': typeof ApiPublicCronReleaseStaleOrdersRoute
  '/api/public/cron/service-reminders': typeof ApiPublicCronServiceRemindersRoute
  '/api/public/photo/$': typeof ApiPublicPhotoSplatRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
  '/scooters/': typeof AuthenticatedCustomerScootersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/bulk': typeof BulkRoute
  '/contact': typeof ContactRoute
  '/find-parts': typeof FindPartsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/manage-login': typeof ManageLoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/returns': typeof ReturnsRoute
  '/service': typeof ServiceRoute
  '/shipping': typeof ShippingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/track': typeof TrackRoute
  '/trade': typeof TradeRouteWithChildren
  '/warranty': typeof WarrantyRoute
  '/booking/$token': typeof BookingTokenRoute
  '/manage/about': typeof ManageAboutRoute
  '/manage/all-products': typeof ManageAllProductsRoute
  '/manage/bookings': typeof ManageBookingsRoute
  '/manage/brand-catalogue': typeof ManageBrandCatalogueRoute
  '/manage/catalogue': typeof ManageCatalogueRoute
  '/manage/counter-sales': typeof ManageCounterSalesRoute
  '/manage/domain': typeof ManageDomainRoute
  '/manage/enquiries': typeof ManageEnquiriesRoute
  '/manage/home': typeof ManageHomeRoute
  '/manage/import': typeof ManageImportRoute
  '/manage/payment-reports': typeof ManagePaymentReportsRoute
  '/manage/razorpay-review': typeof ManageRazorpayReviewRoute
  '/manage/reviews': typeof ManageReviewsRoute
  '/manage/scooters': typeof ManageScootersRoute
  '/manage/settings': typeof ManageSettingsRoute
  '/manage/staff': typeof ManageStaffRoute
  '/manage/summary': typeof ManageSummaryRoute
  '/manage/suppliers': typeof ManageSuppliersRoute
  '/manage/trade': typeof ManageTradeRoute
  '/manage/vendors': typeof ManageVendorsRoute
  '/order/$id': typeof OrderIdRoute
  '/quote/$token': typeof QuoteTokenRoute
  '/trade/pad': typeof TradePadRoute
  '/manage': typeof ManageIndexRoute
  '/brand': typeof AuthenticatedCustomerBrandRoute
  '/cart': typeof AuthenticatedCustomerCartRoute
  '/categories': typeof AuthenticatedCustomerCategoriesRoute
  '/checkout': typeof AuthenticatedCustomerCheckoutRoute
  '/offers': typeof AuthenticatedCustomerOffersRoute
  '/shop': typeof AuthenticatedCustomerShopRoute
  '/api/public/catalogue': typeof ApiPublicCatalogueRoute
  '/api/public/client-error': typeof ApiPublicClientErrorRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/manage/customers/$customerId': typeof ManageCustomersCustomerIdRoute
  '/manage/orders/$orderId': typeof ManageOrdersOrderIdRoute
  '/manage/products/$productId': typeof ManageProductsProductIdRoute
  '/manage/customers': typeof ManageCustomersIndexRoute
  '/manage/orders': typeof ManageOrdersIndexRoute
  '/category/$slug': typeof AuthenticatedCustomerCategorySlugRoute
  '/product/$slug': typeof AuthenticatedCustomerProductSlugRoute
  '/scooters/$slug': typeof AuthenticatedCustomerScootersSlugRoute
  '/api/public/cron/cart-reminders': typeof ApiPublicCronCartRemindersRoute
  '/api/public/cron/daily-summary': typeof ApiPublicCronDailySummaryRoute
  '/api/public/cron/release-stale-orders': typeof ApiPublicCronReleaseStaleOrdersRoute
  '/api/public/cron/service-reminders': typeof ApiPublicCronServiceRemindersRoute
  '/api/public/photo/$': typeof ApiPublicPhotoSplatRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
  '/scooters': typeof AuthenticatedCustomerScootersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/bulk': typeof BulkRoute
  '/contact': typeof ContactRoute
  '/find-parts': typeof FindPartsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/manage': typeof ManageRouteWithChildren
  '/manage-login': typeof ManageLoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/returns': typeof ReturnsRoute
  '/service': typeof ServiceRoute
  '/shipping': typeof ShippingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/track': typeof TrackRoute
  '/trade': typeof TradeRouteWithChildren
  '/warranty': typeof WarrantyRoute
  '/booking/$token': typeof BookingTokenRoute
  '/manage/about': typeof ManageAboutRoute
  '/manage/all-products': typeof ManageAllProductsRoute
  '/manage/bookings': typeof ManageBookingsRoute
  '/manage/brand-catalogue': typeof ManageBrandCatalogueRoute
  '/manage/catalogue': typeof ManageCatalogueRoute
  '/manage/counter-sales': typeof ManageCounterSalesRoute
  '/manage/customers': typeof ManageCustomersRouteWithChildren
  '/manage/domain': typeof ManageDomainRoute
  '/manage/enquiries': typeof ManageEnquiriesRoute
  '/manage/home': typeof ManageHomeRoute
  '/manage/import': typeof ManageImportRoute
  '/manage/orders': typeof ManageOrdersRouteWithChildren
  '/manage/payment-reports': typeof ManagePaymentReportsRoute
  '/manage/razorpay-review': typeof ManageRazorpayReviewRoute
  '/manage/reviews': typeof ManageReviewsRoute
  '/manage/scooters': typeof ManageScootersRoute
  '/manage/settings': typeof ManageSettingsRoute
  '/manage/staff': typeof ManageStaffRoute
  '/manage/summary': typeof ManageSummaryRoute
  '/manage/suppliers': typeof ManageSuppliersRoute
  '/manage/trade': typeof ManageTradeRoute
  '/manage/vendors': typeof ManageVendorsRoute
  '/order/$id': typeof OrderIdRoute
  '/quote/$token': typeof QuoteTokenRoute
  '/trade/pad': typeof TradePadRoute
  '/manage/': typeof ManageIndexRoute
  '/_authenticated/_customer/brand': typeof AuthenticatedCustomerBrandRoute
  '/_authenticated/_customer/cart': typeof AuthenticatedCustomerCartRoute
  '/_authenticated/_customer/categories': typeof AuthenticatedCustomerCategoriesRoute
  '/_authenticated/_customer/checkout': typeof AuthenticatedCustomerCheckoutRoute
  '/_authenticated/_customer/offers': typeof AuthenticatedCustomerOffersRoute
  '/_authenticated/_customer/shop': typeof AuthenticatedCustomerShopRoute
  '/api/public/catalogue': typeof ApiPublicCatalogueRoute
  '/api/public/client-error': typeof ApiPublicClientErrorRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/manage/customers/$customerId': typeof ManageCustomersCustomerIdRoute
  '/manage/orders/$orderId': typeof ManageOrdersOrderIdRoute
  '/manage/products/$productId': typeof ManageProductsProductIdRoute
  '/manage/customers/': typeof ManageCustomersIndexRoute
  '/manage/orders/': typeof ManageOrdersIndexRoute
  '/_authenticated/_customer/category/$slug': typeof AuthenticatedCustomerCategorySlugRoute
  '/_authenticated/_customer/product/$slug': typeof AuthenticatedCustomerProductSlugRoute
  '/_authenticated/_customer/scooters/$slug': typeof AuthenticatedCustomerScootersSlugRoute
  '/api/public/cron/cart-reminders': typeof ApiPublicCronCartRemindersRoute
  '/api/public/cron/daily-summary': typeof ApiPublicCronDailySummaryRoute
  '/api/public/cron/release-stale-orders': typeof ApiPublicCronReleaseStaleOrdersRoute
  '/api/public/cron/service-reminders': typeof ApiPublicCronServiceRemindersRoute
  '/api/public/photo/$': typeof ApiPublicPhotoSplatRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
  '/_authenticated/_customer/scooters/': typeof AuthenticatedCustomerScootersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/bulk'
    | '/contact'
    | '/find-parts'
    | '/forgot-password'
    | '/manage'
    | '/manage-login'
    | '/privacy'
    | '/reset-password'
    | '/returns'
    | '/service'
    | '/shipping'
    | '/sitemap.xml'
    | '/terms'
    | '/track'
    | '/trade'
    | '/warranty'
    | '/booking/$token'
    | '/manage/about'
    | '/manage/all-products'
    | '/manage/bookings'
    | '/manage/brand-catalogue'
    | '/manage/catalogue'
    | '/manage/counter-sales'
    | '/manage/customers'
    | '/manage/domain'
    | '/manage/enquiries'
    | '/manage/home'
    | '/manage/import'
    | '/manage/orders'
    | '/manage/payment-reports'
    | '/manage/razorpay-review'
    | '/manage/reviews'
    | '/manage/scooters'
    | '/manage/settings'
    | '/manage/staff'
    | '/manage/summary'
    | '/manage/suppliers'
    | '/manage/trade'
    | '/manage/vendors'
    | '/order/$id'
    | '/quote/$token'
    | '/trade/pad'
    | '/manage/'
    | '/brand'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/offers'
    | '/shop'
    | '/api/public/catalogue'
    | '/api/public/client-error'
    | '/api/public/health'
    | '/api/public/razorpay-webhook'
    | '/manage/customers/$customerId'
    | '/manage/orders/$orderId'
    | '/manage/products/$productId'
    | '/manage/customers/'
    | '/manage/orders/'
    | '/category/$slug'
    | '/product/$slug'
    | '/scooters/$slug'
    | '/api/public/cron/cart-reminders'
    | '/api/public/cron/daily-summary'
    | '/api/public/cron/release-stale-orders'
    | '/api/public/cron/service-reminders'
    | '/api/public/photo/$'
    | '/api/public/whatsapp/webhook'
    | '/scooters/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/bulk'
    | '/contact'
    | '/find-parts'
    | '/forgot-password'
    | '/manage-login'
    | '/privacy'
    | '/reset-password'
    | '/returns'
    | '/service'
    | '/shipping'
    | '/sitemap.xml'
    | '/terms'
    | '/track'
    | '/trade'
    | '/warranty'
    | '/booking/$token'
    | '/manage/about'
    | '/manage/all-products'
    | '/manage/bookings'
    | '/manage/brand-catalogue'
    | '/manage/catalogue'
    | '/manage/counter-sales'
    | '/manage/domain'
    | '/manage/enquiries'
    | '/manage/home'
    | '/manage/import'
    | '/manage/payment-reports'
    | '/manage/razorpay-review'
    | '/manage/reviews'
    | '/manage/scooters'
    | '/manage/settings'
    | '/manage/staff'
    | '/manage/summary'
    | '/manage/suppliers'
    | '/manage/trade'
    | '/manage/vendors'
    | '/order/$id'
    | '/quote/$token'
    | '/trade/pad'
    | '/manage'
    | '/brand'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/offers'
    | '/shop'
    | '/api/public/catalogue'
    | '/api/public/client-error'
    | '/api/public/health'
    | '/api/public/razorpay-webhook'
    | '/manage/customers/$customerId'
    | '/manage/orders/$orderId'
    | '/manage/products/$productId'
    | '/manage/customers'
    | '/manage/orders'
    | '/category/$slug'
    | '/product/$slug'
    | '/scooters/$slug'
    | '/api/public/cron/cart-reminders'
    | '/api/public/cron/daily-summary'
    | '/api/public/cron/release-stale-orders'
    | '/api/public/cron/service-reminders'
    | '/api/public/photo/$'
    | '/api/public/whatsapp/webhook'
    | '/scooters'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/bulk'
    | '/contact'
    | '/find-parts'
    | '/forgot-password'
    | '/manage'
    | '/manage-login'
    | '/privacy'
    | '/reset-password'
    | '/returns'
    | '/service'
    | '/shipping'
    | '/sitemap.xml'
    | '/terms'
    | '/track'
    | '/trade'
    | '/warranty'
    | '/booking/$token'
    | '/manage/about'
    | '/manage/all-products'
    | '/manage/bookings'
    | '/manage/brand-catalogue'
    | '/manage/catalogue'
    | '/manage/counter-sales'
    | '/manage/customers'
    | '/manage/domain'
    | '/manage/enquiries'
    | '/manage/home'
    | '/manage/import'
    | '/manage/orders'
    | '/manage/payment-reports'
    | '/manage/razorpay-review'
    | '/manage/reviews'
    | '/manage/scooters'
    | '/manage/settings'
    | '/manage/staff'
    | '/manage/summary'
    | '/manage/suppliers'
    | '/manage/trade'
    | '/manage/vendors'
    | '/order/$id'
    | '/quote/$token'
    | '/trade/pad'
    | '/manage/'
    | '/_authenticated/_customer/brand'
    | '/_authenticated/_customer/cart'
    | '/_authenticated/_customer/categories'
    | '/_authenticated/_customer/checkout'
    | '/_authenticated/_customer/offers'
    | '/_authenticated/_customer/shop'
    | '/api/public/catalogue'
    | '/api/public/client-error'
    | '/api/public/health'
    | '/api/public/razorpay-webhook'
    | '/manage/customers/$customerId'
    | '/manage/orders/$orderId'
    | '/manage/products/$productId'
    | '/manage/customers/'
    | '/manage/orders/'
    | '/_authenticated/_customer/category/$slug'
    | '/_authenticated/_customer/product/$slug'
    | '/_authenticated/_customer/scooters/$slug'
    | '/api/public/cron/cart-reminders'
    | '/api/public/cron/daily-summary'
    | '/api/public/cron/release-stale-orders'
    | '/api/public/cron/service-reminders'
    | '/api/public/photo/$'
    | '/api/public/whatsapp/webhook'
    | '/_authenticated/_customer/scooters/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  BulkRoute: typeof BulkRoute
  ContactRoute: typeof ContactRoute
  FindPartsRoute: typeof FindPartsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ManageRoute: typeof ManageRouteWithChildren
  ManageLoginRoute: typeof ManageLoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ReturnsRoute: typeof ReturnsRoute
  ServiceRoute: typeof ServiceRoute
  ShippingRoute: typeof ShippingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  TrackRoute: typeof TrackRoute
  TradeRoute: typeof TradeRouteWithChildren
  WarrantyRoute: typeof WarrantyRoute
  BookingTokenRoute: typeof BookingTokenRoute
  OrderIdRoute: typeof OrderIdRoute
  QuoteTokenRoute: typeof QuoteTokenRoute
  AuthenticatedCustomerBrandRoute: typeof AuthenticatedCustomerBrandRoute
  AuthenticatedCustomerCartRoute: typeof AuthenticatedCustomerCartRoute
  AuthenticatedCustomerCategoriesRoute: typeof AuthenticatedCustomerCategoriesRoute
  AuthenticatedCustomerCheckoutRoute: typeof AuthenticatedCustomerCheckoutRoute
  AuthenticatedCustomerOffersRoute: typeof AuthenticatedCustomerOffersRoute
  AuthenticatedCustomerShopRoute: typeof AuthenticatedCustomerShopRoute
  ApiPublicCatalogueRoute: typeof ApiPublicCatalogueRoute
  ApiPublicClientErrorRoute: typeof ApiPublicClientErrorRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicRazorpayWebhookRoute: typeof ApiPublicRazorpayWebhookRoute
  AuthenticatedCustomerCategorySlugRoute: typeof AuthenticatedCustomerCategorySlugRoute
  AuthenticatedCustomerProductSlugRoute: typeof AuthenticatedCustomerProductSlugRoute
  AuthenticatedCustomerScootersSlugRoute: typeof AuthenticatedCustomerScootersSlugRoute
  ApiPublicCronCartRemindersRoute: typeof ApiPublicCronCartRemindersRoute
  ApiPublicCronDailySummaryRoute: typeof ApiPublicCronDailySummaryRoute
  ApiPublicCronReleaseStaleOrdersRoute: typeof ApiPublicCronReleaseStaleOrdersRoute
  ApiPublicCronServiceRemindersRoute: typeof ApiPublicCronServiceRemindersRoute
  ApiPublicPhotoSplatRoute: typeof ApiPublicPhotoSplatRoute
  ApiPublicWhatsappWebhookRoute: typeof ApiPublicWhatsappWebhookRoute
  AuthenticatedCustomerScootersIndexRoute: typeof AuthenticatedCustomerScootersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulk': {
      id: '/bulk'
      path: '/bulk'
      fullPath: '/bulk'
      preLoaderRoute: typeof BulkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-parts': {
      id: '/find-parts'
      path: '/find-parts'
      fullPath: '/find-parts'
      preLoaderRoute: typeof FindPartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage': {
      id: '/manage'
      path: '/manage'
      fullPath: '/manage'
      preLoaderRoute: typeof ManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage-login': {
      id: '/manage-login'
      path: '/manage-login'
      fullPath: '/manage-login'
      preLoaderRoute: typeof ManageLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns': {
      id: '/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service': {
      id: '/service'
      path: '/service'
      fullPath: '/service'
      preLoaderRoute: typeof ServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping': {
      id: '/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof ShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade': {
      id: '/trade'
      path: '/trade'
      fullPath: '/trade'
      preLoaderRoute: typeof TradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warranty': {
      id: '/warranty'
      path: '/warranty'
      fullPath: '/warranty'
      preLoaderRoute: typeof WarrantyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/$token': {
      id: '/booking/$token'
      path: '/booking/$token'
      fullPath: '/booking/$token'
      preLoaderRoute: typeof BookingTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/': {
      id: '/manage/'
      path: '/'
      fullPath: '/manage/'
      preLoaderRoute: typeof ManageIndexRouteImport
      parentRoute: typeof ManageRoute
    }
    '/manage/about': {
      id: '/manage/about'
      path: '/about'
      fullPath: '/manage/about'
      preLoaderRoute: typeof ManageAboutRouteImport
      parentRoute: typeof ManageRoute
    }
    '/manage/all-products': {
      id: '/manage/all-products'
      path: '/all-products'
      fullPath: '/manage/all-products'
      preLoaderRoute: typeof ManageAllProductsRouteImport
      parentRoute: typeof ManageRoute
    }
    '/manage/bookings': {
      id: '/manage/bookings'
      path: '/bookings'
      fullPath: '/manage/bookings'
      preLoaderRoute: typeof ManageBookingsRouteImport
      parentRoute: typeof ManageRoute
    }
    '/manage/brand-catalogue': {
      id: '/manage/brand-catalogue'
      path: '/brand-catalogue'
      fullPath: '/manage/brand-catalogue'
      preLoaderRoute: typeof ManageBrandCatalogueRouteImport
      parentRoute: typeof ManageRoute
    }
    '/manage/catalogue': {
      id: '/manage/catalogue'
      path: '/catalogue'
      fullPath: '/manage/catalogue'
      preLoaderRoute: typeof ManageCatalogueRouteImport
      parentRoute: typeof ManageRoute
    }
    '/manage/counter-sales': {
      id: '/manage/counter-sales'
      path: '/counter-sales'
      fullPath: '/manage/counter-sales'
      preLoaderRoute: typeof ManageCounterSalesRouteImport
      parentRoute: typeof ManageRoute
    }
    '/manage/customers': {
      id: '/manage/customers'
      path: '/customers'
      fullPath: '/manage/customers'
      preLoaderRoute: typeof ManageCustomersRouteImport
      parentRoute: typeof ManageRoute
    }
    '/manage/domain': {
      id: '/manage/domain'
      path: '/domain'
      fullPath: '/manage/domain'
      preLoaderRoute: typeof ManageDomainRouteImport
      parentRoute: typeof ManageRoute
    }
    '/manage/enquiries': {
      id: '/manage/enquiries'
      path: '/enquiries'
      fullPath: '/manage/enquiries'
      preLoaderRoute: typeof ManageEnquiriesRouteImport
      parentRoute: typeof ManageRoute
    }
    '/manage/home': {
      id: '/manage/home'
      path: '/home'
      fullPath: '/manage/home'
      preLoaderRoute: typeof ManageHomeRouteImport
      parentRoute: typeof ManageRoute
    }
    '/manage/import': {
      id: '/manage/import'
      path: '/import'
      fullPath: '/manage/import'
      preLoaderRoute: typeof ManageImportRouteImport
      parentRoute: typeof ManageRoute
    }
    '/manage/orders': {
      id: '/manage/orders'
      path: '/orders'
      fullPath: '/manage/orders'
      preLoaderRoute: typeof ManageOrdersRouteImport
      parentRoute: typeof ManageRoute
    }
    '/manage/payment-reports': {
      id: '/manage/payment-reports'
      path: '/payment-reports'
      fullPath: '/manage/payment-reports'
      preLoaderRoute: typeof ManagePaymentReportsRouteImport
      parentRoute: typeof ManageRoute
    }
    '/manage/razorpay-review': {
      id: '/manage/razorpay-review'
      path: '/razorpay-review'
      fullPath: '/manage/razorpay-review'
      preLoaderRoute: typeof ManageRazorpayReviewRouteImport
      parentRoute: typeof ManageRoute
    }
    '/manage/reviews': {
      id: '/manage/reviews'
      path: '/reviews'
      fullPath: '/manage/reviews'
      preLoaderRoute: typeof ManageReviewsRouteImport
      parentRoute: typeof ManageRoute
    }
    '/manage/scooters': {
      id: '/manage/scooters'
      path: '/scooters'
      fullPath: '/manage/scooters'
      preLoaderRoute: typeof ManageScootersRouteImport
      parentRoute: typeof ManageRoute
    }
    '/manage/settings': {
      id: '/manage/settings'
      path: '/settings'
      fullPath: '/manage/settings'
      preLoaderRoute: typeof ManageSettingsRouteImport
      parentRoute: typeof ManageRoute
    }
    '/manage/staff': {
      id: '/manage/staff'
      path: '/staff'
      fullPath: '/manage/staff'
      preLoaderRoute: typeof ManageStaffRouteImport
      parentRoute: typeof ManageRoute
    }
    '/manage/summary': {
      id: '/manage/summary'
      path: '/summary'
      fullPath: '/manage/summary'
      preLoaderRoute: typeof ManageSummaryRouteImport
      parentRoute: typeof ManageRoute
    }
    '/manage/suppliers': {
      id: '/manage/suppliers'
      path: '/suppliers'
      fullPath: '/manage/suppliers'
      preLoaderRoute: typeof ManageSuppliersRouteImport
      parentRoute: typeof ManageRoute
    }
    '/manage/trade': {
      id: '/manage/trade'
      path: '/trade'
      fullPath: '/manage/trade'
      preLoaderRoute: typeof ManageTradeRouteImport
      parentRoute: typeof ManageRoute
    }
    '/manage/vendors': {
      id: '/manage/vendors'
      path: '/vendors'
      fullPath: '/manage/vendors'
      preLoaderRoute: typeof ManageVendorsRouteImport
      parentRoute: typeof ManageRoute
    }
    '/order/$id': {
      id: '/order/$id'
      path: '/order/$id'
      fullPath: '/order/$id'
      preLoaderRoute: typeof OrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote/$token': {
      id: '/quote/$token'
      path: '/quote/$token'
      fullPath: '/quote/$token'
      preLoaderRoute: typeof QuoteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade/pad': {
      id: '/trade/pad'
      path: '/pad'
      fullPath: '/trade/pad'
      preLoaderRoute: typeof TradePadRouteImport
      parentRoute: typeof TradeRoute
    }
    '/_authenticated/_customer/brand': {
      id: '/_authenticated/_customer/brand'
      path: '/brand'
      fullPath: '/brand'
      preLoaderRoute: typeof AuthenticatedCustomerBrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_customer/cart': {
      id: '/_authenticated/_customer/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof AuthenticatedCustomerCartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_customer/categories': {
      id: '/_authenticated/_customer/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AuthenticatedCustomerCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_customer/checkout': {
      id: '/_authenticated/_customer/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof AuthenticatedCustomerCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_customer/offers': {
      id: '/_authenticated/_customer/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof AuthenticatedCustomerOffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_customer/shop': {
      id: '/_authenticated/_customer/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof AuthenticatedCustomerShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/catalogue': {
      id: '/api/public/catalogue'
      path: '/api/public/catalogue'
      fullPath: '/api/public/catalogue'
      preLoaderRoute: typeof ApiPublicCatalogueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/client-error': {
      id: '/api/public/client-error'
      path: '/api/public/client-error'
      fullPath: '/api/public/client-error'
      preLoaderRoute: typeof ApiPublicClientErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/razorpay-webhook': {
      id: '/api/public/razorpay-webhook'
      path: '/api/public/razorpay-webhook'
      fullPath: '/api/public/razorpay-webhook'
      preLoaderRoute: typeof ApiPublicRazorpayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/customers/': {
      id: '/manage/customers/'
      path: '/'
      fullPath: '/manage/customers/'
      preLoaderRoute: typeof ManageCustomersIndexRouteImport
      parentRoute: typeof ManageCustomersRoute
    }
    '/manage/customers/$customerId': {
      id: '/manage/customers/$customerId'
      path: '/$customerId'
      fullPath: '/manage/customers/$customerId'
      preLoaderRoute: typeof ManageCustomersCustomerIdRouteImport
      parentRoute: typeof ManageCustomersRoute
    }
    '/manage/orders/': {
      id: '/manage/orders/'
      path: '/'
      fullPath: '/manage/orders/'
      preLoaderRoute: typeof ManageOrdersIndexRouteImport
      parentRoute: typeof ManageOrdersRoute
    }
    '/manage/orders/$orderId': {
      id: '/manage/orders/$orderId'
      path: '/$orderId'
      fullPath: '/manage/orders/$orderId'
      preLoaderRoute: typeof ManageOrdersOrderIdRouteImport
      parentRoute: typeof ManageOrdersRoute
    }
    '/manage/products/$productId': {
      id: '/manage/products/$productId'
      path: '/products/$productId'
      fullPath: '/manage/products/$productId'
      preLoaderRoute: typeof ManageProductsProductIdRouteImport
      parentRoute: typeof ManageRoute
    }
    '/_authenticated/_customer/category/$slug': {
      id: '/_authenticated/_customer/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof AuthenticatedCustomerCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_customer/product/$slug': {
      id: '/_authenticated/_customer/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof AuthenticatedCustomerProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_customer/scooters/': {
      id: '/_authenticated/_customer/scooters/'
      path: '/scooters'
      fullPath: '/scooters/'
      preLoaderRoute: typeof AuthenticatedCustomerScootersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_customer/scooters/$slug': {
      id: '/_authenticated/_customer/scooters/$slug'
      path: '/scooters/$slug'
      fullPath: '/scooters/$slug'
      preLoaderRoute: typeof AuthenticatedCustomerScootersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/cart-reminders': {
      id: '/api/public/cron/cart-reminders'
      path: '/api/public/cron/cart-reminders'
      fullPath: '/api/public/cron/cart-reminders'
      preLoaderRoute: typeof ApiPublicCronCartRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/daily-summary': {
      id: '/api/public/cron/daily-summary'
      path: '/api/public/cron/daily-summary'
      fullPath: '/api/public/cron/daily-summary'
      preLoaderRoute: typeof ApiPublicCronDailySummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/release-stale-orders': {
      id: '/api/public/cron/release-stale-orders'
      path: '/api/public/cron/release-stale-orders'
      fullPath: '/api/public/cron/release-stale-orders'
      preLoaderRoute: typeof ApiPublicCronReleaseStaleOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/service-reminders': {
      id: '/api/public/cron/service-reminders'
      path: '/api/public/cron/service-reminders'
      fullPath: '/api/public/cron/service-reminders'
      preLoaderRoute: typeof ApiPublicCronServiceRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/photo/$': {
      id: '/api/public/photo/$'
      path: '/api/public/photo/$'
      fullPath: '/api/public/photo/$'
      preLoaderRoute: typeof ApiPublicPhotoSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whatsapp/webhook': {
      id: '/api/public/whatsapp/webhook'
      path: '/api/public/whatsapp/webhook'
      fullPath: '/api/public/whatsapp/webhook'
      preLoaderRoute: typeof ApiPublicWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ManageCustomersRouteChildren {
  ManageCustomersCustomerIdRoute: typeof ManageCustomersCustomerIdRoute
  ManageCustomersIndexRoute: typeof ManageCustomersIndexRoute
}

const ManageCustomersRouteChildren: ManageCustomersRouteChildren = {
  ManageCustomersCustomerIdRoute: ManageCustomersCustomerIdRoute,
  ManageCustomersIndexRoute: ManageCustomersIndexRoute,
}

const ManageCustomersRouteWithChildren = ManageCustomersRoute._addFileChildren(
  ManageCustomersRouteChildren,
)

interface ManageOrdersRouteChildren {
  ManageOrdersOrderIdRoute: typeof ManageOrdersOrderIdRoute
  ManageOrdersIndexRoute: typeof ManageOrdersIndexRoute
}

const ManageOrdersRouteChildren: ManageOrdersRouteChildren = {
  ManageOrdersOrderIdRoute: ManageOrdersOrderIdRoute,
  ManageOrdersIndexRoute: ManageOrdersIndexRoute,
}

const ManageOrdersRouteWithChildren = ManageOrdersRoute._addFileChildren(
  ManageOrdersRouteChildren,
)

interface ManageRouteChildren {
  ManageAboutRoute: typeof ManageAboutRoute
  ManageAllProductsRoute: typeof ManageAllProductsRoute
  ManageBookingsRoute: typeof ManageBookingsRoute
  ManageBrandCatalogueRoute: typeof ManageBrandCatalogueRoute
  ManageCatalogueRoute: typeof ManageCatalogueRoute
  ManageCounterSalesRoute: typeof ManageCounterSalesRoute
  ManageCustomersRoute: typeof ManageCustomersRouteWithChildren
  ManageDomainRoute: typeof ManageDomainRoute
  ManageEnquiriesRoute: typeof ManageEnquiriesRoute
  ManageHomeRoute: typeof ManageHomeRoute
  ManageImportRoute: typeof ManageImportRoute
  ManageOrdersRoute: typeof ManageOrdersRouteWithChildren
  ManagePaymentReportsRoute: typeof ManagePaymentReportsRoute
  ManageRazorpayReviewRoute: typeof ManageRazorpayReviewRoute
  ManageReviewsRoute: typeof ManageReviewsRoute
  ManageScootersRoute: typeof ManageScootersRoute
  ManageSettingsRoute: typeof ManageSettingsRoute
  ManageStaffRoute: typeof ManageStaffRoute
  ManageSummaryRoute: typeof ManageSummaryRoute
  ManageSuppliersRoute: typeof ManageSuppliersRoute
  ManageTradeRoute: typeof ManageTradeRoute
  ManageVendorsRoute: typeof ManageVendorsRoute
  ManageIndexRoute: typeof ManageIndexRoute
  ManageProductsProductIdRoute: typeof ManageProductsProductIdRoute
}

const ManageRouteChildren: ManageRouteChildren = {
  ManageAboutRoute: ManageAboutRoute,
  ManageAllProductsRoute: ManageAllProductsRoute,
  ManageBookingsRoute: ManageBookingsRoute,
  ManageBrandCatalogueRoute: ManageBrandCatalogueRoute,
  ManageCatalogueRoute: ManageCatalogueRoute,
  ManageCounterSalesRoute: ManageCounterSalesRoute,
  ManageCustomersRoute: ManageCustomersRouteWithChildren,
  ManageDomainRoute: ManageDomainRoute,
  ManageEnquiriesRoute: ManageEnquiriesRoute,
  ManageHomeRoute: ManageHomeRoute,
  ManageImportRoute: ManageImportRoute,
  ManageOrdersRoute: ManageOrdersRouteWithChildren,
  ManagePaymentReportsRoute: ManagePaymentReportsRoute,
  ManageRazorpayReviewRoute: ManageRazorpayReviewRoute,
  ManageReviewsRoute: ManageReviewsRoute,
  ManageScootersRoute: ManageScootersRoute,
  ManageSettingsRoute: ManageSettingsRoute,
  ManageStaffRoute: ManageStaffRoute,
  ManageSummaryRoute: ManageSummaryRoute,
  ManageSuppliersRoute: ManageSuppliersRoute,
  ManageTradeRoute: ManageTradeRoute,
  ManageVendorsRoute: ManageVendorsRoute,
  ManageIndexRoute: ManageIndexRoute,
  ManageProductsProductIdRoute: ManageProductsProductIdRoute,
}

const ManageRouteWithChildren =
  ManageRoute._addFileChildren(ManageRouteChildren)

interface TradeRouteChildren {
  TradePadRoute: typeof TradePadRoute
}

const TradeRouteChildren: TradeRouteChildren = {
  TradePadRoute: TradePadRoute,
}

const TradeRouteWithChildren = TradeRoute._addFileChildren(TradeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  BulkRoute: BulkRoute,
  ContactRoute: ContactRoute,
  FindPartsRoute: FindPartsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ManageRoute: ManageRouteWithChildren,
  ManageLoginRoute: ManageLoginRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ReturnsRoute: ReturnsRoute,
  ServiceRoute: ServiceRoute,
  ShippingRoute: ShippingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  TrackRoute: TrackRoute,
  TradeRoute: TradeRouteWithChildren,
  WarrantyRoute: WarrantyRoute,
  BookingTokenRoute: BookingTokenRoute,
  OrderIdRoute: OrderIdRoute,
  QuoteTokenRoute: QuoteTokenRoute,
  AuthenticatedCustomerBrandRoute: AuthenticatedCustomerBrandRoute,
  AuthenticatedCustomerCartRoute: AuthenticatedCustomerCartRoute,
  AuthenticatedCustomerCategoriesRoute: AuthenticatedCustomerCategoriesRoute,
  AuthenticatedCustomerCheckoutRoute: AuthenticatedCustomerCheckoutRoute,
  AuthenticatedCustomerOffersRoute: AuthenticatedCustomerOffersRoute,
  AuthenticatedCustomerShopRoute: AuthenticatedCustomerShopRoute,
  ApiPublicCatalogueRoute: ApiPublicCatalogueRoute,
  ApiPublicClientErrorRoute: ApiPublicClientErrorRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicRazorpayWebhookRoute: ApiPublicRazorpayWebhookRoute,
  AuthenticatedCustomerCategorySlugRoute:
    AuthenticatedCustomerCategorySlugRoute,
  AuthenticatedCustomerProductSlugRoute: AuthenticatedCustomerProductSlugRoute,
  AuthenticatedCustomerScootersSlugRoute:
    AuthenticatedCustomerScootersSlugRoute,
  ApiPublicCronCartRemindersRoute: ApiPublicCronCartRemindersRoute,
  ApiPublicCronDailySummaryRoute: ApiPublicCronDailySummaryRoute,
  ApiPublicCronReleaseStaleOrdersRoute: ApiPublicCronReleaseStaleOrdersRoute,
  ApiPublicCronServiceRemindersRoute: ApiPublicCronServiceRemindersRoute,
  ApiPublicPhotoSplatRoute: ApiPublicPhotoSplatRoute,
  ApiPublicWhatsappWebhookRoute: ApiPublicWhatsappWebhookRoute,
  AuthenticatedCustomerScootersIndexRoute:
    AuthenticatedCustomerScootersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
